package com.tcbs.automation.config.intermana;

public class IntermanaKey {
  public static final String INTERMANA_CREATE_RESPONSE = "INTERMANA_CREATE_RESPONSE";
  public static final String INTERMANA_UPDATE_RESPONSE = "INTERMANA_UPDATE_RESPONSE";
  public static final String INTERMANA_DETAIL_RESPONSE = "INTERMANA_DETAIL_RESPONSE";
  public static final String INTERMANA_USER_LIST_RESPONSE = "INTERMANA_USER_LIST_RESPONSE";
  public static final String INTERMANA_SUB_USER_LIST_RESPONSE = "INTERMANA_SUB_USER_LIST_RESPONSE";
  public static final String INTERMANA_SUB_DETAIL_RESPONSE = "INTERMANA_SUB_DETAIL_RESPONSE";
  public static final String INTERMANA_UPDATE_PERIODICALLY_RESPONSE = "INTERMANA_UPDATE_PERIODICALLY_RESPONSE";


}
