package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_ACCOUNT_ODS")
public class OggAccountOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "ACCOUNT_NUMBER")
  private String accountNumber;
  @Column(name = "CUSTOMER")
  private String customer;
  @Column(name = "PRODCAT")
  private String prodcat;
  @Column(name = "ACCOUNT_TITLE_1")
  private String accountTitle1;
  @Column(name = "ACCOUNT_TITLE_2")
  private String accountTitle2;
  @Column(name = "SHORT_TITLE")
  private String shortTitle;
  @Column(name = "MNEMONIC")
  private String mnemonic;
  @Column(name = "POSITION_TYPE")
  private String positionType;
  @Column(name = "CURRENCY")
  private String currency;
  @Column(name = "CURRENCY_MARKET")
  private String currencyMarket;
  @Column(name = "LIMIT_REF")
  private String limitRef;
  @Column(name = "ACCOUNT_OFFICER")
  private String accountOfficer;
  @Column(name = "OTHER_OFFICER")
  private String otherOfficer;
  @Column(name = "POSTING_RESTRICT")
  private String postingRestrict;
  @Column(name = "RECONCILE_ACCT")
  private String reconcileAcct;
  @Column(name = "INTEREST_LIQU_ACCT")
  private String interestLiquAcct;
  @Column(name = "INTEREST_COMP_ACCT")
  private String interestCompAcct;
  @Column(name = "INT_NO_BOOKING")
  private String intNoBooking;
  @Column(name = "REFERAL_CODE")
  private String referalCode;
  @Column(name = "WAIVE_LEDGER_FEE")
  private String waiveLedgerFee;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "CONDITION_GROUP")
  private String conditionGroup;
  @Column(name = "INACTIV_MARKER")
  private String inactivMarker;
  @Column(name = "OPEN_ACTUAL_BAL")
  private String openActualBal;
  @Column(name = "OPEN_CLEARED_BAL")
  private String openClearedBal;
  @Column(name = "ONLINE_ACTUAL_BAL")
  private String onlineActualBal;
  @Column(name = "ONLINE_CLEARED_BAL")
  private String onlineClearedBal;
  @Column(name = "WORKING_BALANCE")
  private String workingBalance;
  @Column(name = "DATE_LAST_CR_CUST")
  private Date dateLastCrCust;
  @Column(name = "AMNT_LAST_CR_CUST")
  private String amntLastCrCust;
  @Column(name = "TRAN_LAST_CR_CUST")
  private String tranLastCrCust;
  @Column(name = "DATE_LAST_CR_AUTO")
  private Date dateLastCrAuto;
  @Column(name = "AMNT_LAST_CR_AUTO")
  private String amntLastCrAuto;
  @Column(name = "TRAN_LAST_CR_AUTO")
  private String tranLastCrAuto;
  @Column(name = "DATE_LAST_CR_BANK")
  private Date dateLastCrBank;
  @Column(name = "AMNT_LAST_CR_BANK")
  private String amntLastCrBank;
  @Column(name = "TRAN_LAST_CR_BANK")
  private String tranLastCrBank;
  @Column(name = "DATE_LAST_DR_CUST")
  private Date dateLastDrCust;
  @Column(name = "AMNT_LAST_DR_CUST")
  private String amntLastDrCust;
  @Column(name = "TRAN_LAST_DR_CUST")
  private String tranLastDrCust;
  @Column(name = "DATE_LAST_DR_AUTO")
  private Date dateLastDrAuto;
  @Column(name = "AMNT_LAST_DR_AUTO")
  private String amntLastDrAuto;
  @Column(name = "TRAN_LAST_DR_AUTO")
  private String tranLastDrAuto;
  @Column(name = "DATE_LAST_DR_BANK")
  private Date dateLastDrBank;
  @Column(name = "AMNT_LAST_DR_BANK")
  private String amntLastDrBank;
  @Column(name = "TRAN_LAST_DR_BANK")
  private String tranLastDrBank;
  @Column(name = "CAP_DATE_CHARGE")
  private String capDateCharge;
  @Column(name = "CAP_DATE_CR_INT")
  private String capDateCrInt;
  @Column(name = "CAP_DATE_C2_INT")
  private String capDateC2Int;
  @Column(name = "CAP_DATE_DR_INT")
  private String capDateDrInt;
  @Column(name = "CAP_DATE_D2_INT")
  private String capDateD2Int;
  @Column(name = "CAP_BACK_VALUE")
  private Date capBackValue;
  @Column(name = "ACCR_CHG_CATEG")
  private String accrChgCateg;
  @Column(name = "ACCR_CHG_TRANS")
  private String accrChgTrans;
  @Column(name = "ACCR_CHG_AMOUNT")
  private String accrChgAmount;
  @Column(name = "ACCR_CHG_SUSP")
  private String accrChgSusp;
  @Column(name = "ACCR_CR_CATEG")
  private String accrCrCateg;
  @Column(name = "ACCR_CR_TRANS")
  private String accrCrTrans;
  @Column(name = "ACCR_CR_AMOUNT")
  private String accrCrAmount;
  @Column(name = "ACCR_CR_SUSP")
  private String accrCrSusp;
  @Column(name = "ACCR_CR2_CATEG")
  private String accrCr2Categ;
  @Column(name = "ACCR_CR2_TRANS")
  private String accrCr2Trans;
  @Column(name = "ACCR_CR2_AMOUNT")
  private String accrCr2Amount;
  @Column(name = "ACCR_CR2_SUSP")
  private String accrCr2Susp;
  @Column(name = "ACCR_DR_CATEG")
  private String accrDrCateg;
  @Column(name = "ACCR_DR_TRANS")
  private String accrDrTrans;
  @Column(name = "ACCR_DR_AMOUNT")
  private String accrDrAmount;
  @Column(name = "ACCR_DR_SUSP")
  private String accrDrSusp;
  @Column(name = "ACCR_DR2_CATEG")
  private String accrDr2Categ;
  @Column(name = "ACCR_DR2_TRANS")
  private String accrDr2Trans;
  @Column(name = "ACCR_DR2_AMOUNT")
  private String accrDr2Amount;
  @Column(name = "ACCR_DR2_SUSP")
  private String accrDr2Susp;
  @Column(name = "CONSOL_KEY")
  private String consolKey;
  @Column(name = "INT_LIQU_TYPE")
  private String intLiquType;
  @Column(name = "INT_LIQU_ACCT")
  private String intLiquAcct;
  @Column(name = "INT_LIQ_CCY")
  private String intLiqCcy;
  @Column(name = "PASSBOOK")
  private String passbook;
  @Column(name = "START_YEAR_BAL")
  private String startYearBal;
  @Column(name = "OPENING_DATE")
  private Date openingDate;
  @Column(name = "VALUE_DATE")
  private String valueDate;
  @Column(name = "CREDIT_MOVEMENT")
  private String creditMovement;
  @Column(name = "DEBIT_MOVEMENT")
  private String debitMovement;
  @Column(name = "VALUE_DATED_BAL")
  private String valueDatedBal;
  @Column(name = "CONTINGENT_BAL_CR")
  private String contingentBalCr;
  @Column(name = "CONTINGENT_BAL_DR")
  private String contingentBalDr;
  @Column(name = "OPEN_CATEGORY")
  private String openCategory;
  @Column(name = "OPEN_VAL_DATED_BAL")
  private String openValDatedBal;
  @Column(name = "ACCT_CREDIT_INT")
  private String acctCreditInt;
  @Column(name = "ACCT_DEBIT_INT")
  private String acctDebitInt;
  @Column(name = "LINK_TO_LIMIT")
  private String linkToLimit;
  @Column(name = "CLOSURE_DATE")
  private Date closureDate;
  @Column(name = "LOCKED_WITH_LIMIT")
  private String lockedWithLimit;
  @Column(name = "CHARGE_ACCOUNT")
  private String chargeAccount;
  @Column(name = "CHARGE_CCY")
  private String chargeCcy;
  @Column(name = "CHARGE_MKT")
  private String chargeMkt;
  @Column(name = "INTEREST_CCY")
  private String interestCcy;
  @Column(name = "INTEREST_MKT")
  private String interestMkt;
  @Column(name = "CON_CHARGE_ACCR")
  private String conChargeAccr;
  @Column(name = "CON_INTEREST_ACCR")
  private String conInterestAccr;
  @Column(name = "ALT_ACCT_TYPE")
  private String altAcctType;
  @Column(name = "ALT_ACCT_ID")
  private String altAcctId;
  @Column(name = "PREMIUM_TYPE")
  private String premiumType;
  @Column(name = "CAP_DATE_PRM")
  private String capDatePrm;
  @Column(name = "PREMIUM_FREQ")
  private String premiumFreq;
  @Column(name = "APR")
  private String apr;
  @Column(name = "JOINT_HOLDER")
  private String jointHolder;
  @Column(name = "RELATION_CODE")
  private String relationCode;
  @Column(name = "JOINT_NOTES")
  private String jointNotes;
  @Column(name = "ALLOW_NETTING")
  private String allowNetting;
  @Column(name = "LEDG_RECO_WITH")
  private String ledgRecoWith;
  @Column(name = "STMT_RECO_WITH")
  private String stmtRecoWith;
  @Column(name = "OUR_EXT_ACCT_NO")
  private String ourExtAcctNo;
  @Column(name = "RECO_TOLERANCE")
  private String recoTolerance;
  @Column(name = "PENDING_ID")
  private String pendingId;
  @Column(name = "TOTAL_PENDING")
  private String totalPending;
  @Column(name = "STOCK_CONTROL_TYPE")
  private String stockControlType;
  @Column(name = "SERIAL_NO_FORMAT")
  private String serialNoFormat;
  @Column(name = "AUTO_PAY_ACCT")
  private String autoPayAcct;
  @Column(name = "ORIG_CCY_PAYMENT")
  private String origCcyPayment;
  @Column(name = "AUTO_REC_CCY")
  private String autoRecCcy;
  @Column(name = "ORIGINAL_ACCT")
  private String originalAcct;
  @Column(name = "FROM_DATE")
  private String fromDate;
  @Column(name = "LOCKED_AMOUNT")
  private String lockedAmount;
  @Column(name = "DISPO_OFFICER")
  private String dispoOfficer;
  @Column(name = "DISPO_EXEMPT")
  private String dispoExempt;
  @Column(name = "TAX_SUSPEND")
  private String taxSuspend;
  @Column(name = "TAX_AT_SETTLE")
  private String taxAtSettle;
  @Column(name = "ICA_MAIN_ACCOUNT")
  private String icaMainAccount;
  @Column(name = "ICA_DISTRIB_RATIO")
  private String icaDistribRatio;
  @Column(name = "ICA_MAIN_ACCT_IND")
  private String icaMainAcctInd;
  @Column(name = "ICA_DISTRIB_TYPE")
  private String icaDistribType;
  @Column(name = "ICA_POST_INTEREST")
  private String icaPostInterest;
  @Column(name = "ICA_MAIN_RATIO")
  private String icaMainRatio;
  @Column(name = "ICA_NEW_MAIN_ACC")
  private String icaNewMainAcc;
  @Column(name = "ICA_START_DATE")
  private Date icaStartDate;
  @Column(name = "ICA_ADD_REMOVE")
  private String icaAddRemove;
  @Column(name = "ICA_BACK_VALUE")
  private Date icaBackValue;
  @Column(name = "ICA_MAIN_ACCT")
  private String icaMainAcct;
  @Column(name = "ICA_MAIN_DATE")
  private String icaMainDate;
  @Column(name = "LIQUIDATION_MODE")
  private String liquidationMode;
  @Column(name = "OVERDUE_STATUS")
  private String overdueStatus;
  @Column(name = "HVT_FLAG")
  private String hvtFlag;
  @Column(name = "SINGLE_LIMIT")
  private String singleLimit;
  @Column(name = "CONTINGENT_INT")
  private String contingentInt;
  @Column(name = "ALL_IN_ONE_PRODUCT")
  private String allInOneProduct;
  @Column(name = "ER_VALUE_DATE")
  private String erValueDate;
  @Column(name = "ER_BALANCE")
  private String erBalance;
  @Column(name = "EP_BALANCE")
  private String epBalance;
  @Column(name = "SB_GROUP_ID")
  private String sbGroupId;
  @Column(name = "OPEN_AVAILABLE_BAL")
  private String openAvailableBal;
  @Column(name = "AVAILABLE_DATE")
  private String availableDate;
  @Column(name = "AV_AUTH_DB_MVMT")
  private String avAuthDbMvmt;
  @Column(name = "AV_NAU_DB_MVMT")
  private String avNauDbMvmt;
  @Column(name = "AV_AUTH_CR_MVMT")
  private String avAuthCrMvmt;
  @Column(name = "AV_NAU_CR_MVMT")
  private String avNauCrMvmt;
  @Column(name = "AVAILABLE_BAL")
  private String availableBal;
  @Column(name = "FORWARD_MVMTS")
  private String forwardMvmts;
  @Column(name = "CREDIT_CHECK")
  private String creditCheck;
  @Column(name = "AVAILABLE_BAL_UPD")
  private String availableBalUpd;
  @Column(name = "CONSOLIDATE_ENT")
  private String consolidateEnt;
  @Column(name = "MAX_SUB_ACCOUNT")
  private String maxSubAccount;
  @Column(name = "MASTER_ACCOUNT")
  private String masterAccount;
  @Column(name = "LOCK_INC_THIS_MVMT")
  private String lockIncThisMvmt;
  @Column(name = "CLOSED_ONLINE")
  private String closedOnline;
  @Column(name = "NEXT_AF_DATE")
  private Date nextAfDate;
  @Column(name = "NEXT_ACCT_CAP")
  private Date nextAcctCap;
  @Column(name = "NEXT_EXP_DATE")
  private Date nextExpDate;
  @Column(name = "DATE_LAST_UPDATE")
  private Date dateLastUpdate;
  @Column(name = "NEXT_STMT_DATE")
  private String nextStmtDate;
  @Column(name = "EXPOSURE_DATES")
  private String exposureDates;
  @Column(name = "PORTFOLIO_NO")
  private String portfolioNo;
  @Column(name = "SHADOW_ACCOUNT")
  private String shadowAccount;
  @Column(name = "FWD_ENTRY_HOLD")
  private String fwdEntryHold;
  @Column(name = "FIRST_AF_DATE")
  private Date firstAfDate;
  @Column(name = "CASH_POOL_GROUP")
  private String cashPoolGroup;
  @Column(name = "OPEN_ASSET_TYPE")
  private String openAssetType;
  @Column(name = "LAST_COM_CHG_DATE")
  private Date lastComChgDate;
  @Column(name = "IC_CHARGE_ID")
  private String icChargeId;
  @Column(name = "IC_NEXT_CAP_DATE")
  private Date icNextCapDate;
  @Column(name = "IC_PRODUCT")
  private String icProduct;
  @Column(name = "IC_LST_PROD_CAP")
  private String icLstProdCap;
  @Column(name = "ARRANGEMENT_ID")
  private String arrangementId;
  @Column(name = "ACC_DEB_LIMIT")
  private String accDebLimit;
  @Column(name = "MANDATE_APPL")
  private String mandateAppl;
  @Column(name = "MANDATE_REG")
  private String mandateReg;
  @Column(name = "MANDATE_RECORD")
  private String mandateRecord;
  @Column(name = "DR_ADJ_AMOUNT")
  private String drAdjAmount;
  @Column(name = "DR2_ADJ_AMOUNT")
  private String dr2AdjAmount;
  @Column(name = "CR_ADJ_AMOUNT")
  private String crAdjAmount;
  @Column(name = "CR2_ADJ_AMOUNT")
  private String cr2AdjAmount;
  @Column(name = "EVENT")
  private String event;
  @Column(name = "FIELD")
  private String field;
  @Column(name = "OPERAND")
  private String operand;
  @Column(name = "VALUE")
  private String value;
  @Column(name = "MV_ALERT_RES6")
  private String mvAlertRes6;
  @Column(name = "MV_ALERT_RES5")
  private String mvAlertRes5;
  @Column(name = "MV_ALERT_RES4")
  private String mvAlertRes4;
  @Column(name = "MV_ALERT_RES3")
  private String mvAlertRes3;
  @Column(name = "MV_ALERT_RES2")
  private String mvAlertRes2;
  @Column(name = "MV_ALERT_RES1")
  private String mvAlertRes1;
  @Column(name = "REQUEST_ID")
  private String requestId;
  @Column(name = "OVERRIDE")
  private String override;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
