package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_AZ_ACCOUNT_ODS")
public class OggAzAccountOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "ACCOUNT_NUMBER")
  private String accountNumber;
  @Column(name = "CUSTOMER")
  private String customer;
  @Column(name = "CATEGORY")
  private String category;
  @Column(name = "CURRENCY")
  private String currency;
  @Column(name = "ALL_IN_ONE_PRODUCT")
  private String allInOneProduct;
  @Column(name = "PRINCIPAL")
  private String principal;
  @Column(name = "ORIG_PRINCIPAL")
  private String origPrincipal;
  @Column(name = "VALUE_DATE")
  private Date valueDate;
  @Column(name = "MATURITY_DATE")
  private String maturityDate;
  @Column(name = "ORIG_MAT_DATE")
  private Date origMatDate;
  @Column(name = "INTEREST_RATE")
  private String interestRate;
  @Column(name = "PENAL_RATE")
  private String penalRate;
  @Column(name = "TAX_E_I")
  private String taxEI;
  @Column(name = "TAX_ON")
  private String taxOn;
  @Column(name = "TAX_KEY")
  private String taxKey;
  @Column(name = "INTEREST_LIQU_ACCT")
  private String interestLiquAcct;
  @Column(name = "REPAY_ACCOUNT")
  private String repayAccount;
  @Column(name = "REPAY_STO_ACCT")
  private String repayStoAcct;
  @Column(name = "REP_INT_BANK")
  private String repIntBank;
  @Column(name = "REP_BEN_BANK")
  private String repBenBank;
  @Column(name = "REP_BEN_ACCT")
  private String repBenAcct;
  @Column(name = "NOMINATED_ACCOUNT")
  private String nominatedAccount;
  @Column(name = "NOM_INT_BANK")
  private String nomIntBank;
  @Column(name = "NOM_BEN_BANK")
  private String nomBenBank;
  @Column(name = "NOM_BEN_ACCT")
  private String nomBenAcct;
  @Column(name = "CHARGE_KEY")
  private String chargeKey;
  @Column(name = "DRAWDOWN_AMOUNT")
  private String drawdownAmount;
  @Column(name = "AMOUNT_V_DATE")
  private Date amountVDate;
  @Column(name = "DD_INT_RATE")
  private String ddIntRate;
  @Column(name = "REDEMPTION_AMT")
  private String redemptionAmt;
  @Column(name = "SUB_AZ_ACCT")
  private String subAzAcct;
  @Column(name = "ADDITIONAL_SPREAD")
  private String additionalSpread;
  @Column(name = "CHG_FROM_RED_AMT")
  private String chgFromRedAmt;
  @Column(name = "EARLY_RED_INT")
  private String earlyRedInt;
  @Column(name = "WAIVE_CHG")
  private String waiveChg;
  @Column(name = "CHARGE_CODE")
  private String chargeCode;
  @Column(name = "CHARGE_CCY")
  private String chargeCcy;
  @Column(name = "CHARGE_AMOUNT")
  private String chargeAmount;
  @Column(name = "CHARGE_AMT_LCY")
  private String chargeAmtLcy;
  @Column(name = "CHARGE_DATE")
  private String chargeDate;
  @Column(name = "CHG_LIQ_ACCT")
  private String chgLiqAcct;
  @Column(name = "CHARGE_IMMED")
  private String chargeImmed;
  @Column(name = "CHG_PL_ACCT")
  private String chgPlAcct;
  @Column(name = "TAX_CODE")
  private String taxCode;
  @Column(name = "TAX_AMOUNT")
  private String taxAmount;
  @Column(name = "TAX_AMT_LCY")
  private String taxAmtLcy;
  @Column(name = "TAX_ACCT")
  private String taxAcct;
  @Column(name = "SCHEDULES")
  private String schedules;
  @Column(name = "REPAYMENT_TYPE")
  private String repaymentType;
  @Column(name = "CALCULATION_BASE")
  private String calculationBase;
  @Column(name = "INT_ONLY")
  private String intOnly;
  @Column(name = "MAX_INSTL_INT_ONLY")
  private String maxInstlIntOnly;
  @Column(name = "RESIDUAL_PRINCIPAL")
  private String residualPrincipal;
  @Column(name = "TERM_PRIORITY")
  private String termPriority;
  @Column(name = "ROLLOVER_AMT")
  private String rolloverAmt;
  @Column(name = "ROLLOVER_TERM")
  private String rolloverTerm;
  @Column(name = "ROLLOVER_INT_RATE")
  private String rolloverIntRate;
  @Column(name = "ROLLOVER_DATE")
  private Date rolloverDate;
  @Column(name = "FINAL_MATURITY")
  private Date finalMaturity;
  @Column(name = "FORWARD_BACKWARD")
  private String forwardBackward;
  @Column(name = "TYPE_OF_SCHDLE")
  private String typeOfSchdle;
  @Column(name = "AMT_PERCENT")
  private String amtPercent;
  @Column(name = "AMOUNT")
  private String amount;
  @Column(name = "FREQUENCY")
  private String frequency;
  @Column(name = "NUMBER_")
  private String number;
  @Column(name = "RATE_SCH_KEY")
  private String rateSchKey;
  @Column(name = "RATE_SCH_SPREAD")
  private String rateSchSpread;
  @Column(name = "RATE_SCH_OPERND")
  private String rateSchOpernd;
  @Column(name = "RATE_SCH_PERCNT")
  private String rateSchPercnt;
  @Column(name = "SCH_FIXED_RATE")
  private String schFixedRate;
  @Column(name = "PRD_RATE_KEY")
  private String prdRateKey;
  @Column(name = "PI_METHOD")
  private String piMethod;
  @Column(name = "TYPE_B_SYS")
  private String typeBSys;
  @Column(name = "SL_CHARGE_CODE")
  private String slChargeCode;
  @Column(name = "SL_CHG_BASE_AMT")
  private String slChgBaseAmt;
  @Column(name = "SL_CHG_LIQ_ACCT")
  private String slChgLiqAcct;
  @Column(name = "RES_4")
  private String res4;
  @Column(name = "RES_5")
  private String res5;
  @Column(name = "FINAL_DD_IND")
  private String finalDdInd;
  @Column(name = "PRE_CLOSURE_IND")
  private String preClosureInd;
  @Column(name = "DAYS_BEF_EVENT")
  private String daysBefEvent;
  @Column(name = "DEL_CARRIER")
  private String delCarrier;
  @Column(name = "MESSAGE_CLASS")
  private String messageClass;
  @Column(name = "ACTIVITY")
  private String activity;
  @Column(name = "DELIVERY_REF")
  private String deliveryRef;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "REVOLVING_RATIO")
  private String revolvingRatio;
  @Column(name = "REPAY_AMT")
  private String repayAmt;
  @Column(name = "REPAY_V_DATE")
  private Date repayVDate;
  @Column(name = "MAT_DATE")
  private Date matDate;
  @Column(name = "CANCEL_LAST_DD")
  private String cancelLastDd;
  @Column(name = "CC_PR_GRACE_PERIOD")
  private String ccPrGracePeriod;
  @Column(name = "RATE_CHG_SUB_ACC")
  private String rateChgSubAcc;
  @Column(name = "CREDIT_AMOUNT")
  private String creditAmount;
  @Column(name = "REDUCE_LIMIT")
  private String reduceLimit;
  @Column(name = "CONSOL_KEY")
  private String consolKey;
  @Column(name = "LAST_DAY_INCL")
  private String lastDayIncl;
  @Column(name = "MATURITY_INSTR")
  private String maturityInstr;
  @Column(name = "GRACE_PERIOD")
  private String gracePeriod;
  @Column(name = "ORIG_INTEREST_RATE")
  private String origInterestRate;
  @Column(name = "INT_ADJ_AMT")
  private String intAdjAmt;
  @Column(name = "RESERVED_01")
  private String reserved01;
  @Column(name = "LOAN_INT_ADJUST")
  private String loanIntAdjust;
  @Column(name = "INT_CORR_IMMED")
  private String intCorrImmed;
  @Column(name = "CREATE_DATE")
  private String createDate;
  @Column(name = "PRIN_CHG_AMT")
  private String prinChgAmt;
  @Column(name = "PRIN_EFF_DATE")
  private Date prinEffDate;
  @Column(name = "MIN_MAT_DATE")
  private String minMatDate;
  @Column(name = "COMPOUND_TYPE")
  private String compoundType;
  @Column(name = "ROLL_INT_CAP_FQU")
  private String rollIntCapFqu;
  @Column(name = "ROLL_INT_PAY_FQU")
  private String rollIntPayFqu;
  @Column(name = "PAY_INT_AT_MAT")
  private String payIntAtMat;
  @Column(name = "ROLL_AIO_PRODUCT")
  private String rollAioProduct;
  @Column(name = "PAY_INT_AT_PARTRED")
  private String payIntAtPartred;
  @Column(name = "REDEMPTION_DATE")
  private Date redemptionDate;
  @Column(name = "IAS_CLASSIFICATION")
  private String iasClassification;
  @Column(name = "IAS_SUB_TYPE")
  private String iasSubType;
  @Column(name = "MARKET_RATE")
  private String marketRate;
  @Column(name = "MARKET_MARGIN")
  private String marketMargin;
  @Column(name = "CAP_INT_AT_SOD")
  private String capIntAtSod;
  @Column(name = "RESERVED_2")
  private String reserved2;
  @Column(name = "RESERVED_1")
  private String reserved1;
  @Column(name = "STMT_NO")
  private String stmtNo;
  @Column(name = "OVERRIDE")
  private String override;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
