package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_CUSTOMER_ODS")
public class OggCustomerOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "GENDER")
  private String gender;
  @Column(name = "CUSTOMER_CODE")
  private String customerCode;
  @Column(name = "MNEMONIC")
  private String mnemonic;
  @Column(name = "SHORT_NAME")
  private String shortName;
  @Column(name = "NAME_1")
  private String name1;
  @Column(name = "NAME_2")
  private String name2;
  @Column(name = "STREET")
  private String street;
  @Column(name = "ADDRESS")
  private String address;
  @Column(name = "TOWN_COUNTRY")
  private String townCountry;
  @Column(name = "POST_CODE")
  private String postCode;
  @Column(name = "COUNTRY")
  private String country;
  @Column(name = "RELATION_CODE")
  private String relationCode;
  @Column(name = "REL_CUSTOMER")
  private String relCustomer;
  @Column(name = "REVERS_REL_CODE")
  private String reversRelCode;
  @Column(name = "REL_DELIV_OPT")
  private String relDelivOpt;
  @Column(name = "ROLE")
  private String role;
  @Column(name = "ROLE_MORE_INFO")
  private String roleMoreInfo;
  @Column(name = "ROLE_NOTES")
  private String roleNotes;
  @Column(name = "REL_RESERV6")
  private String relReserv6;
  @Column(name = "REL_RESERV5")
  private String relReserv5;
  @Column(name = "REL_RESERV4")
  private String relReserv4;
  @Column(name = "REL_RESERV3")
  private String relReserv3;
  @Column(name = "REL_RESERV2")
  private String relReserv2;
  @Column(name = "REL_RESERV1")
  private String relReserv1;
  @Column(name = "SECTOR")
  private String sector;
  @Column(name = "ACCOUNT_OFFICER")
  private String accountOfficer;
  @Column(name = "OTHER_OFFICER")
  private String otherOfficer;
  @Column(name = "INDUSTRY")
  private String industry;
  @Column(name = "TARGET")
  private String target;
  @Column(name = "NATIONALITY")
  private String nationality;
  @Column(name = "CUSTOMER_STATUS")
  private String customerStatus;
  @Column(name = "RESIDENCE")
  private String residence;
  @Column(name = "CONTACT_DATE")
  private Date contactDate;
  @Column(name = "INTRODUCER")
  private String introducer;
  @Column(name = "TEXT")
  private String text;
  @Column(name = "LEGAL_ID")
  private String legalId;
  @Column(name = "LEGAL_DOC_NAME")
  private String legalDocName;
  @Column(name = "LEGAL_HOLDER_NAME")
  private String legalHolderName;
  @Column(name = "LEGAL_ISS_AUTH")
  private String legalIssAuth;
  @Column(name = "LEGAL_ISS_DATE")
  private String legalIssDate;
  @Column(name = "LEGAL_EXP_DATE")
  private String legalExpDate;
  @Column(name = "OFF_PHONE")
  private String offPhone;
  @Column(name = "REVIEW_FREQUENCY")
  private String reviewFrequency;
  @Column(name = "BIRTH_INCORP_DATE")
  private Date birthIncorpDate;
  @Column(name = "GLOBAL_CUSTOMER")
  private String globalCustomer;
  @Column(name = "CUSTOMER_LIABILITY")
  private String customerLiability;
  @Column(name = "LANGUAGE")
  private String language;
  @Column(name = "POSTING_RESTRICT")
  private String postingRestrict;
  @Column(name = "DISPO_OFFICER")
  private String dispoOfficer;
  @Column(name = "COMPANY_BOOK")
  private String companyBook;
  @Column(name = "CONFID_TXT")
  private String confidTxt;
  @Column(name = "DISPO_EXEMPT")
  private String dispoExempt;
  @Column(name = "ISSUE_CHEQUES")
  private String issueCheques;
  @Column(name = "CLS_CPARTY")
  private String clsCparty;
  @Column(name = "FX_COMM_GROUP_ID")
  private String fxCommGroupId;
  @Column(name = "RESIDENCE_REGION")
  private String residenceRegion;
  @Column(name = "ASSET_CLASS")
  private String assetClass;
  @Column(name = "CUSTOMER_RATING")
  private String customerRating;
  @Column(name = "CR_PROFILE_TYPE")
  private String crProfileType;
  @Column(name = "CR_PROFILE")
  private String crProfile;
  @Column(name = "NO_UPDATE_CRM")
  private String noUpdateCrm;
  @Column(name = "TITLE")
  private String title;
  @Column(name = "GIVEN_NAMES")
  private String givenNames;
  @Column(name = "FAMILY_NAME")
  private String familyName;
  @Column(name = "DATE_OF_BIRTH")
  private Date dateOfBirth;
  @Column(name = "MARITAL_STATUS")
  private String maritalStatus;
  @Column(name = "NO_OF_DEPENDENTS")
  private String noOfDependents;
  @Column(name = "PHONE_1")
  private String phone1;
  @Column(name = "SMS_1")
  private String sms1;
  @Column(name = "EMAIL_1")
  private String email1;
  @Column(name = "ADDR_LOCATION")
  private String addrLocation;
  @Column(name = "EMPLOYMENT_STATUS")
  private String employmentStatus;
  @Column(name = "OCCUPATION")
  private String occupation;
  @Column(name = "JOB_TITLE")
  private String jobTitle;
  @Column(name = "EMPLOYERS_NAME")
  private String employersName;
  @Column(name = "EMPLOYERS_ADD")
  private String employersAdd;
  @Column(name = "EMPLOYERS_BUSS")
  private String employersBuss;
  @Column(name = "EMPLOYMENT_START")
  private String employmentStart;
  @Column(name = "CUSTOMER_CURRENCY")
  private String customerCurrency;
  @Column(name = "SALARY")
  private String salary;
  @Column(name = "ANNUAL_BONUS")
  private String annualBonus;
  @Column(name = "SALARY_DATE_FREQ")
  private String salaryDateFreq;
  @Column(name = "NET_MONTHLY_IN")
  private String netMonthlyIn;
  @Column(name = "NET_MONTHLY_OUT")
  private String netMonthlyOut;
  @Column(name = "RESIDENCE_STATUS")
  private String residenceStatus;
  @Column(name = "RESIDENCE_TYPE")
  private String residenceType;
  @Column(name = "RESIDENCE_SINCE")
  private String residenceSince;
  @Column(name = "RESIDENCE_VALUE")
  private String residenceValue;
  @Column(name = "MORTGAGE_AMT")
  private String mortgageAmt;
  @Column(name = "OTHER_FIN_REL")
  private String otherFinRel;
  @Column(name = "OTHER_FIN_INST")
  private String otherFinInst;
  @Column(name = "COMM_TYPE")
  private String commType;
  @Column(name = "PREF_CHANNEL")
  private String prefChannel;
  @Column(name = "ALLOW_BULK_PROCESS")
  private String allowBulkProcess;
  @Column(name = "LEGAL_ID_DOC_NAME")
  private String legalIdDocName;
  @Column(name = "INTERESTS")
  private String interests;
  @Column(name = "FAX_1")
  private String fax1;
  @Column(name = "PREVIOUS_NAME")
  private String previousName;
  @Column(name = "CHANGE_DATE")
  private String changeDate;
  @Column(name = "CHANGE_REASON")
  private String changeReason;
  @Column(name = "CUSTOMER_SINCE")
  private Date customerSince;
  @Column(name = "CUSTOMER_TYPE")
  private String customerType;
  @Column(name = "RESERVED_51")
  private String reserved51;
  @Column(name = "DATE_LAST_VERIFIED")
  private String dateLastVerified;
  @Column(name = "SPOKEN_LANGUAGE")
  private String spokenLanguage;
  @Column(name = "PASTIMES")
  private String pastimes;
  @Column(name = "FURTHER_DETAILS")
  private String furtherDetails;
  @Column(name = "DOMICILE")
  private String domicile;
  @Column(name = "OTHER_NATIONALITY")
  private String otherNationality;
  @Column(name = "CALC_RISK_CLASS")
  private String calcRiskClass;
  @Column(name = "MANUAL_RISK_CLASS")
  private String manualRiskClass;
  @Column(name = "OVERRIDE_REASON")
  private String overrideReason;
  @Column(name = "TAX_ID")
  private String taxId;
  @Column(name = "VIS_TYPE")
  private String visType;
  @Column(name = "VIS_COMMENT")
  private String visComment;
  @Column(name = "VIS_INTERNAL_REVIEW")
  private String visInternalReview;
  @Column(name = "FORMER_VIS_TYPE")
  private String formerVisType;
  @Column(name = "FORMER_VIS_COMMENT")
  private String formerVisComment;
  @Column(name = "RISK_ASSET_TYPE")
  private String riskAssetType;
  @Column(name = "RISK_LEVEL")
  private String riskLevel;
  @Column(name = "RISK_TOLERANCE")
  private String riskTolerance;
  @Column(name = "RISK_FROM_DATE")
  private String riskFromDate;
  @Column(name = "LAST_KYC_REVIEW_DATE")
  private Date lastKycReviewDate;
  @Column(name = "AUTO_NEXT_KYC_REVIEW_DATE")
  private Date autoNextKycReviewDate;
  @Column(name = "MANUAL_NEXT_KYC_REVIEW_DATE")
  private Date manualNextKycReviewDate;
  @Column(name = "LAST_SUIT_REVIEW_DATE")
  private Date lastSuitReviewDate;
  @Column(name = "AUTO_NEXT_SUIT_REVIEW_DATE")
  private Date autoNextSuitReviewDate;
  @Column(name = "MANUAL_NEXT_SUIT_REVIEW_DATE")
  private Date manualNextSuitReviewDate;
  @Column(name = "KYC_RELATIONSHIP")
  private String kycRelationship;
  @Column(name = "MANDATE_APPL")
  private String mandateAppl;
  @Column(name = "MANDATE_REG")
  private String mandateReg;
  @Column(name = "MANDATE_RECORD")
  private String mandateRecord;
  @Column(name = "SECURE_MESSAGE")
  private String secureMessage;
  @Column(name = "AML_CHECK")
  private String amlCheck;
  @Column(name = "AML_RESULT")
  private String amlResult;
  @Column(name = "LAST_AML_RESULT_DATE")
  private Date lastAmlResultDate;
  @Column(name = "KYC_COMPLETE")
  private String kycComplete;
  @Column(name = "INTERNET_BANKING_SERVICE")
  private String internetBankingService;
  @Column(name = "MOBILE_BANKING_SERVICE")
  private String mobileBankingService;
  @Column(name = "REPORT_TEMPLATE")
  private String reportTemplate;
  @Column(name = "HOLDINGS_PIVOT")
  private String holdingsPivot;
  @Column(name = "MERGED_TO")
  private String mergedTo;
  @Column(name = "MERGED_STATUS")
  private String mergedStatus;
  @Column(name = "ALT_CUS_ID")
  private String altCusId;
  @Column(name = "EXTERN_SYS_ID")
  private String externSysId;
  @Column(name = "EXTERN_CUS_ID")
  private String externCusId;
  @Column(name = "SOCIAL_NTW_IDS")
  private String socialNtwIds;
  @Column(name = "PERSON_ENTITY_ID")
  private String personEntityId;
  @Column(name = "REG_COUNTRY")
  private String regCountry;
  @Column(name = "RESERVED_30")
  private String reserved30;
  @Column(name = "RESERVED_29")
  private String reserved29;
  @Column(name = "RESERVED_28")
  private String reserved28;
  @Column(name = "RESERVED_27")
  private String reserved27;
  @Column(name = "RESERVED_26")
  private String reserved26;
  @Column(name = "RESERVED_25")
  private String reserved25;
  @Column(name = "RESERVED_24")
  private String reserved24;
  @Column(name = "RESERVED_23")
  private String reserved23;
  @Column(name = "RESERVED_22")
  private String reserved22;
  @Column(name = "RESERVED_21")
  private String reserved21;
  @Column(name = "RESERVED_20")
  private String reserved20;
  @Column(name = "RESERVED_19")
  private String reserved19;
  @Column(name = "RESERVED_18")
  private String reserved18;
  @Column(name = "RESERVED_17")
  private String reserved17;
  @Column(name = "RESERVED_16")
  private String reserved16;
  @Column(name = "RESERVED_15")
  private String reserved15;
  @Column(name = "RESERVED_14")
  private String reserved14;
  @Column(name = "RESERVED_13")
  private String reserved13;
  @Column(name = "RESERVED_12")
  private String reserved12;
  @Column(name = "RESERVED_11")
  private String reserved11;
  @Column(name = "RESERVED_10")
  private String reserved10;
  @Column(name = "RESERVED_09")
  private String reserved09;
  @Column(name = "RESERVED_08")
  private String reserved08;
  @Column(name = "RESERVED_07")
  private String reserved07;
  @Column(name = "RESERVED_06")
  private String reserved06;
  @Column(name = "RESERVED_05")
  private String reserved05;
  @Column(name = "RESERVED_04")
  private String reserved04;
  @Column(name = "RESERVED_03")
  private String reserved03;
  @Column(name = "RESERVED_02")
  private String reserved02;
  @Column(name = "RESERVED_01")
  private String reserved01;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "OVERRIDE")
  private String override;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
