package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_COMPANY_ODS")
public class OggCompanyOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "COMPANY_CODE")
  private String companyCode;
  @Column(name = "COMPANY_NAME")
  private String companyName;
  @Column(name = "NAME_ADDRESS")
  private String nameAddress;
  @Column(name = "MNEMONIC")
  private String mnemonic;
  @Column(name = "LANGUAGE_CODE")
  private String languageCode;
  @Column(name = "STAT_REP_AREA")
  private String statRepArea;
  @Column(name = "STAT_REP_NAME")
  private String statRepName;
  @Column(name = "STAT_REP_DELIV")
  private String statRepDeliv;
  @Column(name = "MGMT_REP_AREA")
  private String mgmtRepArea;
  @Column(name = "MGMT_REP_NAME")
  private String mgmtRepName;
  @Column(name = "MGMT_REP_DELIV")
  private String mgmtRepDeliv;
  @Column(name = "CONSOLIDATION_MARK")
  private String consolidationMark;
  @Column(name = "DEFAULT_NO_OF_AUTH")
  private String defaultNoOfAuth;
  @Column(name = "PGM_AUTOM_ID")
  private String pgmAutomId;
  @Column(name = "LOCAL_COUNTRY")
  private String localCountry;
  @Column(name = "LOCAL_REGION")
  private String localRegion;
  @Column(name = "LOCAL_CURRENCY")
  private String localCurrency;
  @Column(name = "RATE_SYSTEM")
  private String rateSystem;
  @Column(name = "CUSTOMER_COMPANY")
  private String customerCompany;
  @Column(name = "CUSTOMER_MNEMONIC")
  private String customerMnemonic;
  @Column(name = "DEFAULT_CUST_COM")
  private String defaultCustCom;
  @Column(name = "DEFAULT_CUST_MNE")
  private String defaultCustMne;
  @Column(name = "SPCL_CUST_FILE")
  private String spclCustFile;
  @Column(name = "SPCL_CUST_COM")
  private String spclCustCom;
  @Column(name = "SPCL_CUST_MNE")
  private String spclCustMne;
  @Column(name = "DEFAULT_FINAN_COM")
  private String defaultFinanCom;
  @Column(name = "DEFAULT_FINAN_MNE")
  private String defaultFinanMne;
  @Column(name = "SPCL_FIN_FILE")
  private String spclFinFile;
  @Column(name = "SPCL_FIN_COM")
  private String spclFinCom;
  @Column(name = "SPCL_FIN_MNE")
  private String spclFinMne;
  @Column(name = "CURRENCY_COMPANY")
  private String currencyCompany;
  @Column(name = "CURRENCY_MNEMONIC")
  private String currencyMnemonic;
  @Column(name = "FINAN_FINAN_COM")
  private String finanFinanCom;
  @Column(name = "FINAN_FINAN_MNE")
  private String finanFinanMne;
  @Column(name = "NOSTRO_COMPANY")
  private String nostroCompany;
  @Column(name = "NOSTRO_MNEMONIC")
  private String nostroMnemonic;
  @Column(name = "NOSTRO_SUB_DIV")
  private String nostroSubDiv;
  @Column(name = "INTER_COM_CATEGORY")
  private String interComCategory;
  @Column(name = "APPLICATIONS")
  private String applications;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "LOCAL_PROCESS_NAME")
  private String localProcessName;
  @Column(name = "DEFAULT_RATE_ALLOW")
  private String defaultRateAllow;
  @Column(name = "FCY_CONV_TOLER_MIN")
  private String fcyConvTolerMin;
  @Column(name = "FCY_CONV_TOLER_MAX")
  private String fcyConvTolerMax;
  @Column(name = "CHARGE_CALCULATION")
  private String chargeCalculation;
  @Column(name = "FINANCIAL_YEAR_END")
  private String financialYearEnd;
  @Column(name = "INACTIVITY_MONTHS")
  private String inactivityMonths;
  @Column(name = "SUB_DIVISION_CODE")
  private String subDivisionCode;
  @Column(name = "SWIFT_ADD_COM_REF")
  private String swiftAddComRef;
  @Column(name = "LAST_YEAR_END")
  private Date lastYearEnd;
  @Column(name = "DC_TOLERANCE_RATE")
  private String dcToleranceRate;
  @Column(name = "DC_MAX_ROUND_AMT")
  private String dcMaxRoundAmt;
  @Column(name = "ACCT_CHECKDIG_TYPE")
  private String acctCheckdigType;
  @Column(name = "ACC_BKNO_PREFIX")
  private String accBknoPrefix;
  @Column(name = "ACCOUNT_MASK")
  private String accountMask;
  @Column(name = "BOOK")
  private String book;
  @Column(name = "RELATIVE_TIME")
  private String relativeTime;
  @Column(name = "SEPARATE_EOD")
  private String separateEod;
  @Column(name = "CONS_KEY_CO")
  private String consKeyCo;
  @Column(name = "COMPANY_GROUP")
  private String companyGroup;
  @Column(name = "OFFICIAL_HOLIDAY")
  private String officialHoliday;
  @Column(name = "BRANCH_HOLIDAY")
  private String branchHoliday;
  @Column(name = "BATCH_HOLIDAY")
  private String batchHoliday;
  @Column(name = "BRANCH_CLOSED")
  private String branchClosed;
  @Column(name = "FINANCIAL_COM")
  private String financialCom;
  @Column(name = "FINANCIAL_MNE")
  private String financialMne;
  @Column(name = "DEF_RATING_AGENCY")
  private String defRatingAgency;
  @Column(name = "CUST_RETENTION")
  private String custRetention;
  @Column(name = "PROSPECT_ALLOWED")
  private String prospectAllowed;
  @Column(name = "COMPANY_SCHEMA")
  private String companySchema;
  @Column(name = "IBAN_BANK_ID")
  private String ibanBankId;
  @Column(name = "IBAN_BRANCH_ID")
  private String ibanBranchId;
  @Column(name = "TIME_ZONE")
  private String timeZone;
  @Column(name = "RESERVED_4")
  private String reserved4;
  @Column(name = "RESERVED_3")
  private String reserved3;
  @Column(name = "RESERVED_2")
  private String reserved2;
  @Column(name = "RESERVED_1")
  private String reserved1;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
