package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_LD_LOANS_AND_DEPOSITS_ODS")
public class OggLdLoansAndDepositsOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "CONTRACT_NO_")
  private String contractNo;
  @Column(name = "CUSTOMER_ID")
  private String customerId;
  @Column(name = "CURRENCY")
  private String currency;
  @Column(name = "CURRENCY_MARKET")
  private String currencyMarket;
  @Column(name = "AMOUNT")
  private String amount;
  @Column(name = "BUS_DAY_DEFN")
  private String busDayDefn;
  @Column(name = "VALUE_DATE")
  private Date valueDate;
  @Column(name = "FIN_MAT_DATE")
  private Date finMatDate;
  @Column(name = "LIMIT_REFERENCE")
  private String limitReference;
  @Column(name = "THIRD_PARTY_REF")
  private String thirdPartyRef;
  @Column(name = "CUSTOMER_REF")
  private String customerRef;
  @Column(name = "CATEGORY")
  private String category;
  @Column(name = "DRAWDOWN_ACCOUNT")
  private String drawdownAccount;
  @Column(name = "INT_RATE_TYPE")
  private String intRateType;
  @Column(name = "INTEREST_BASIS")
  private String interestBasis;
  @Column(name = "INT_PAYMT_METHOD")
  private String intPaymtMethod;
  @Column(name = "INTEREST_RATE")
  private String interestRate;
  @Column(name = "INTEREST_KEY")
  private String interestKey;
  @Column(name = "INTEREST_SPREAD")
  private String interestSpread;
  @Column(name = "ACCRUAL_PARAM")
  private String accrualParam;
  @Column(name = "INT_REF_NUMBER")
  private String intRefNumber;
  @Column(name = "MIS_INTEREST_KEY")
  private String misInterestKey;
  @Column(name = "MIS_INTEREST_RATE")
  private String misInterestRate;
  @Column(name = "CAPITALISATION")
  private String capitalisation;
  @Column(name = "TOT_INTEREST_AMT")
  private String totInterestAmt;
  @Column(name = "INT_START_DATE")
  private Date intStartDate;
  @Column(name = "INT_END_DATE")
  private Date intEndDate;
  @Column(name = "BAND_LEVEL_IND")
  private String bandLevelInd;
  @Column(name = "TAX_PRINCIPAL_KEY")
  private String taxPrincipalKey;
  @Column(name = "TAX_INT_KEY")
  private String taxIntKey;
  @Column(name = "TAX_COMMISSION_KEY")
  private String taxCommissionKey;
  @Column(name = "W_H_TAX_ALT")
  private String wHTaxAlt;
  @Column(name = "W_H_TAX_RATE_KEY")
  private String wHTaxRateKey;
  @Column(name = "LIQUIDATION_CODE")
  private String liquidationCode;
  @Column(name = "COMM_CALC_METHOD")
  private String commCalcMethod;
  @Column(name = "COMM_PAYMT_METHOD")
  private String commPaymtMethod;
  @Column(name = "COMM_RATE")
  private String commRate;
  @Column(name = "TOTAL_COMM_AMOUNT")
  private String totalCommAmount;
  @Column(name = "CHRG_CODE")
  private String chrgCode;
  @Column(name = "CHRG_AMOUNT")
  private String chrgAmount;
  @Column(name = "CHRG_CLAIM_DATE")
  private String chrgClaimDate;
  @Column(name = "CHRG_BOOKED_ON")
  private String chrgBookedOn;
  @Column(name = "CHRG_CAPITALISE")
  private String chrgCapitalise;
  @Column(name = "TOTAL_CAP_CHARGE")
  private String totalCapCharge;
  @Column(name = "LIQUIDATION_MODE")
  private String liquidationMode;
  @Column(name = "OVERDUE_STATUS")
  private String overdueStatus;
  @Column(name = "GRACE_PERIOD")
  private String gracePeriod;
  @Column(name = "GRACE_AMOUNT")
  private String graceAmount;
  @Column(name = "PENALTY_KEY")
  private String penaltyKey;
  @Column(name = "PENALTY_SPREAD")
  private String penaltySpread;
  @Column(name = "MIS_FUNDING_DEPT")
  private String misFundingDept;
  @Column(name = "USE_DEF_PI_RATE")
  private String useDefPiRate;
  @Column(name = "POSITION_TYPE")
  private String positionType;
  @Column(name = "NEG_REF_NUMBER")
  private String negRefNumber;
  @Column(name = "PRINC_FX_RATE")
  private String princFxRate;
  @Column(name = "V_DATE_FOR_P_FX")
  private Date vDateForPFx;
  @Column(name = "TRADE_DATE")
  private Date tradeDate;
  @Column(name = "OTHER_NEG_REF")
  private String otherNegRef;
  @Column(name = "OTHER_FX_RATE")
  private String otherFxRate;
  @Column(name = "V_DATE_OTHER_FX")
  private String vDateOtherFx;
  @Column(name = "PAYING_AGENT")
  private String payingAgent;
  @Column(name = "MAX_CONTRACT_RATE")
  private String maxContractRate;
  @Column(name = "MIN_CONTRACT_RATE")
  private String minContractRate;
  @Column(name = "ACCRUAL_RATE")
  private String accrualRate;
  @Column(name = "REDUCED_RATE")
  private String reducedRate;
  @Column(name = "DELIVERY_LINK")
  private String deliveryLink;
  @Column(name = "WALK_IN_CUST")
  private String walkInCust;
  @Column(name = "PRIN_LIQ_ACCT")
  private String prinLiqAcct;
  @Column(name = "PRIN_BEN_BANK_1")
  private String prinBenBank1;
  @Column(name = "PRIN_BEN_BANK_2")
  private String prinBenBank2;
  @Column(name = "PRIN_ADDRESS")
  private String prinAddress;
  @Column(name = "BENEF_PRIN_ACCT")
  private String benefPrinAcct;
  @Column(name = "INT_LIQ_ACCT")
  private String intLiqAcct;
  @Column(name = "INT_BEN_BANK_1")
  private String intBenBank1;
  @Column(name = "INT_BEN_BANK_2")
  private String intBenBank2;
  @Column(name = "INT_ADDRESS")
  private String intAddress;
  @Column(name = "BEN_INT_ACCT")
  private String benIntAcct;
  @Column(name = "COM_LIQ_ACCT")
  private String comLiqAcct;
  @Column(name = "CHRG_LIQ_ACCT")
  private String chrgLiqAcct;
  @Column(name = "MIS_ACCT_OFFICER")
  private String misAcctOfficer;
  @Column(name = "FEDERAL_FUNDS")
  private String federalFunds;
  @Column(name = "CLEAN_RISK")
  private String cleanRisk;
  @Column(name = "RESERVES")
  private String reserves;
  @Column(name = "SECURED__Y_N")
  private String securedYN;
  @Column(name = "AGREEMENT_DATE")
  private Date agreementDate;
  @Column(name = "CROSS_REF_NO")
  private String crossRefNo;
  @Column(name = "COUNTRY_RISK")
  private String countryRisk;
  @Column(name = "COUNTRY_EXPOSURE")
  private String countryExposure;
  @Column(name = "CENTRAL_BANK_CODE")
  private String centralBankCode;
  @Column(name = "STATUS_CONTROL")
  private String statusControl;
  @Column(name = "STATUS")
  private String status;
  @Column(name = "COMMITMENT_NO")
  private String commitmentNo;
  @Column(name = "L_C_U_TYPE")
  private String lCUType;
  @Column(name = "STA________Y_N")
  private String staYN;
  @Column(name = "L_C_U_CONVERSION")
  private String lCUConversion;
  @Column(name = "L_C_U_CALC_BASE")
  private String lCUCalcBase;
  @Column(name = "COMMT_AVAIL_AMT")
  private String commtAvailAmt;
  @Column(name = "TRANCHE_AMT")
  private String trancheAmt;
  @Column(name = "D_D_START_DATE")
  private String dDStartDate;
  @Column(name = "D_D_END_DATE")
  private String dDEndDate;
  @Column(name = "D_D_MULT_AMT")
  private String dDMultAmt;
  @Column(name = "DRAWDOWN_ISSUE_PRC")
  private String drawdownIssuePrc;
  @Column(name = "DD_FEE_CODE")
  private String ddFeeCode;
  @Column(name = "DD_FEE_AMT")
  private String ddFeeAmt;
  @Column(name = "DRAWDOWN_NET_AMT")
  private String drawdownNetAmt;
  @Column(name = "VD_DATE_ADJUSTMENT")
  private String vdDateAdjustment;
  @Column(name = "ISSUE_PL_AMOUNT")
  private String issuePlAmount;
  @Column(name = "VD_PRIOR_ADJUST")
  private String vdPriorAdjust;
  @Column(name = "PARTICIPANT_NO")
  private String participantNo;
  @Column(name = "COMMIT_DRAWING")
  private String commitDrawing;
  @Column(name = "ISSUE_PRICE")
  private String issuePrice;
  @Column(name = "ISSUE_ACCRUAL")
  private String issueAccrual;
  @Column(name = "REIMBURSE_PRICE")
  private String reimbursePrice;
  @Column(name = "REIMBURSE_AMOUNT")
  private String reimburseAmount;
  @Column(name = "REIMBURSE_PL_AMT")
  private String reimbursePlAmt;
  @Column(name = "REIMBURSE_ACCRUAL")
  private String reimburseAccrual;
  @Column(name = "REIMB_RESERVED")
  private String reimbReserved;
  @Column(name = "PRINC_DIS_ACCT")
  private String princDisAcct;
  @Column(name = "COM_RESERVE_1")
  private String comReserve1;
  @Column(name = "COM_RESERVE_2")
  private String comReserve2;
  @Column(name = "COM_RESERVE_3")
  private String comReserve3;
  @Column(name = "COM_RESERVE_4")
  private String comReserve4;
  @Column(name = "COM_RESERVE_5")
  private String comReserve5;
  @Column(name = "FEE_PAY_ACCOUNT")
  private String feePayAccount;
  @Column(name = "FEE_RESERVE4")
  private String feeReserve4;
  @Column(name = "FEE_RESERVE3")
  private String feeReserve3;
  @Column(name = "FEE_RESERVE2")
  private String feeReserve2;
  @Column(name = "FEE_RESERVE1")
  private String feeReserve1;
  @Column(name = "AMOUNT_INCREASE")
  private String amountIncrease;
  @Column(name = "AMT_V_DATE")
  private Date amtVDate;
  @Column(name = "NEW_INT_RATE")
  private String newIntRate;
  @Column(name = "INT_RATE_V_DATE")
  private Date intRateVDate;
  @Column(name = "NEW_SPREAD")
  private String newSpread;
  @Column(name = "SPREAD_V_DATE")
  private Date spreadVDate;
  @Column(name = "DRAWDOWN_ENT_DATE")
  private Date drawdownEntDate;
  @Column(name = "CANCELLATION_DATE")
  private Date cancellationDate;
  @Column(name = "NEW_COM_RATE")
  private String newComRate;
  @Column(name = "COM_RATE_V_DATE")
  private Date comRateVDate;
  @Column(name = "BK_TO_BK_INFO")
  private String bkToBkInfo;
  @Column(name = "LINK_REFERENCE")
  private String linkReference;
  @Column(name = "CANCELLED_INT")
  private String cancelledInt;
  @Column(name = "TOT_CANCEL_INT_AMT")
  private String totCancelIntAmt;
  @Column(name = "CUST_REMARKS")
  private String custRemarks;
  @Column(name = "ALONE_MERGE_IND")
  private String aloneMergeInd;
  @Column(name = "OUR_REMARKS")
  private String ourRemarks;
  @Column(name = "AUTO_SCHEDS")
  private String autoScheds;
  @Column(name = "DEFINE_SCHEDS")
  private String defineScheds;
  @Column(name = "CONTRACT_TYPE")
  private String contractType;
  @Column(name = "INTEREST_DUE_DATE")
  private String interestDueDate;
  @Column(name = "COMM_DUE_DATE")
  private String commDueDate;
  @Column(name = "INT_REVISION_DATE")
  private String intRevisionDate;
  @Column(name = "MARGIN_REV_DATE")
  private String marginRevDate;
  @Column(name = "PORTFOLIO_NO")
  private String portfolioNo;
  @Column(name = "ACTIVITY")
  private String activity;
  @Column(name = "ADV_SENT")
  private String advSent;
  @Column(name = "TOT_INT_TAX")
  private String totIntTax;
  @Column(name = "TOTAL_W_H_T")
  private String totalWHT;
  @Column(name = "TOT_COM_TAX")
  private String totComTax;
  @Column(name = "TOT_PRINC_TAX")
  private String totPrincTax;
  @Column(name = "SEND_PAYMENT")
  private String sendPayment;
  @Column(name = "SEND_CONFIRMATION")
  private String sendConfirmation;
  @Column(name = "NOTE_DENOM")
  private String noteDenom;
  @Column(name = "NOTE_QUANTITY")
  private String noteQuantity;
  @Column(name = "BROKER_CODE")
  private String brokerCode;
  @Column(name = "BROKERAGE")
  private String brokerage;
  @Column(name = "BROKER_CCY")
  private String brokerCcy;
  @Column(name = "BROKER_AMOUNT")
  private String brokerAmount;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "JOINT_HOLDER")
  private String jointHolder;
  @Column(name = "RELATION_CODE")
  private String relationCode;
  @Column(name = "JOINT_NOTES")
  private String jointNotes;
  @Column(name = "ANNUITY_PAY_METHOD")
  private String annuityPayMethod;
  @Column(name = "RESIDUAL_VALUE")
  private String residualValue;
  @Column(name = "ANNUITY_REPAY_AMT")
  private String annuityRepayAmt;
  @Column(name = "BILL_TXN_AMOUNT")
  private String billTxnAmount;
  @Column(name = "TAX_PRINCIPAL_TYPE")
  private String taxPrincipalType;
  @Column(name = "TAX_INT_TYPE")
  private String taxIntType;
  @Column(name = "TAX_COMMISSN_TYPE")
  private String taxCommissnType;
  @Column(name = "CONTRACT_GRP")
  private String contractGrp;
  @Column(name = "BILL_NUMBER")
  private String billNumber;
  @Column(name = "BILL_REDISC_RATE")
  private String billRediscRate;
  @Column(name = "PRIN_INC_LIMAMT")
  private String prinIncLimamt;
  @Column(name = "INCLUSIVE_CSN")
  private String inclusiveCsn;
  @Column(name = "CSN_CALC_TYPE")
  private String csnCalcType;
  @Column(name = "ASSET_REFERENCE")
  private String assetReference;
  @Column(name = "FIN_CHG_CALC_TYPE")
  private String finChgCalcType;
  @Column(name = "DAYS_PRE_ADVICE")
  private String daysPreAdvice;
  @Column(name = "FV_RATE_KEY")
  private String fvRateKey;
  @Column(name = "FV_MARGIN_KEY")
  private String fvMarginKey;
  @Column(name = "INT_TAX_LCY")
  private String intTaxLcy;
  @Column(name = "NET_INT_TAX_LCY")
  private String netIntTaxLcy;
  @Column(name = "INT_TAX_FCY")
  private String intTaxFcy;
  @Column(name = "NET_INT_TAX_FCY")
  private String netIntTaxFcy;
  @Column(name = "RETURN_INT")
  private String returnInt;
  @Column(name = "RETURN_COM")
  private String returnCom;
  @Column(name = "LD_RESERVED")
  private String ldReserved;
  @Column(name = "HB_CURR_PERIOD")
  private String hbCurrPeriod;
  @Column(name = "YIELD_METHOD")
  private String yieldMethod;
  @Column(name = "MAT_AMOUNT")
  private String matAmount;
  @Column(name = "FLAT_COMM_TYPE")
  private String flatCommType;
  @Column(name = "MATURE_AT_SOD")
  private String matureAtSod;
  @Column(name = "MATURED_ONLINE")
  private String maturedOnline;
  @Column(name = "CURRENCY_CODE")
  private String currencyCode;
  @Column(name = "EXCG_RATE")
  private String excgRate;
  @Column(name = "SETTLEMENT_MARKET")
  private String settlementMarket;
  @Column(name = "CONVERSION_TYPE")
  private String conversionType;
  @Column(name = "REV_CONTINGENT")
  private String revContingent;
  @Column(name = "LAST_DAY_ACCRUAL")
  private String lastDayAccrual;
  @Column(name = "DEFAULTED_VALUE")
  private String defaultedValue;
  @Column(name = "FWD_BWD_KEY")
  private String fwdBwdKey;
  @Column(name = "BASE_DATE_KEY")
  private String baseDateKey;
  @Column(name = "MIS_COF_TYPE")
  private String misCofType;
  @Column(name = "MIS_COF_RATE")
  private String misCofRate;
  @Column(name = "MIS_COF_DEPT")
  private String misCofDept;
  @Column(name = "RED_RECOURSE")
  private String redRecourse;
  @Column(name = "THIRD_PARTY_ID")
  private String thirdPartyId;
  @Column(name = "THIRD_LIM_REF")
  private String thirdLimRef;
  @Column(name = "DEALER_DESK")
  private String dealerDesk;
  @Column(name = "NEGATIVE_RATE")
  private String negativeRate;
  @Column(name = "PENALTY_RATE")
  private String penaltyRate;
  @Column(name = "INT_COLL_METHOD")
  private String intCollMethod;
  @Column(name = "ASSET_CLASS")
  private String assetClass;
  @Column(name = "PROVISION")
  private String provision;
  @Column(name = "PROVISION_AMOUNT")
  private String provisionAmount;
  @Column(name = "PROVISION_METHOD")
  private String provisionMethod;
  @Column(name = "REPAY_CAP")
  private String repayCap;
  @Column(name = "FWD_PROJ")
  private String fwdProj;
  @Column(name = "ROUNDING_RULE")
  private String roundingRule;
  @Column(name = "COMMT_REINITIATE")
  private String commtReinitiate;
  @Column(name = "CURR_PD_PR_AMT")
  private String currPdPrAmt;
  @Column(name = "ONLINE_EFF_DATE")
  private Date onlineEffDate;
  @Column(name = "ONLINE_RPY_TYPE")
  private String onlineRpyType;
  @Column(name = "ONLINE_RPY_AMT")
  private String onlineRpyAmt;
  @Column(name = "IAS_CLASSIFICATION")
  private String iasClassification;
  @Column(name = "IAS_SUBTYPE")
  private String iasSubtype;
  @Column(name = "MARKET_KEY")
  private String marketKey;
  @Column(name = "MARKET_MARGIN")
  private String marketMargin;
  @Column(name = "SPECIAL_INT_BASIS")
  private String specialIntBasis;
  @Column(name = "SPECIAL_COMM_BASIS")
  private String specialCommBasis;
  @Column(name = "COMPOUND_TYPE")
  private String compoundType;
  @Column(name = "COMPOUND_YIELD_METHOD")
  private String compoundYieldMethod;
  @Column(name = "UPDATE_LIMIT_INT")
  private String updateLimitInt;
  @Column(name = "LIVE_INTEREST")
  private String liveInterest;
  @Column(name = "STMT_NO")
  private String stmtNo;
  @Column(name = "OVERRIDE")
  private String override;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
