package com.tcbs.automation.coco;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Entity
@Getter
@Setter
@Table(name = "OGG_MM_MONEY_MARKET_ODS")
public class OggMmMoneyMarketOds {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @NotNull
  @Column(name = "CONTRACT_NO")
  private String contractNo;
  @Column(name = "CUSTOMER_ID")
  private String customerId;
  @Column(name = "CURRENCY")
  private String currency;
  @Column(name = "PRINCIPAL")
  private String principal;
  @Column(name = "DEAL_DATE")
  private Date dealDate;
  @Column(name = "VALUE_DATE")
  private Date valueDate;
  @Column(name = "MATURITY_DATE")
  private String maturityDate;
  @Column(name = "PRODCAT")
  private String prodcat;
  @Column(name = "INT_RATE_TYPE")
  private String intRateType;
  @Column(name = "INTEREST_BASIS")
  private String interestBasis;
  @Column(name = "INTEREST_RATE")
  private String interestRate;
  @Column(name = "INTEREST_KEY")
  private String interestKey;
  @Column(name = "INTEREST_SPREAD_1")
  private String interestSpread1;
  @Column(name = "ACCRUAL_PARAM")
  private String accrualParam;
  @Column(name = "TOT_INTEREST_AMT")
  private String totInterestAmt;
  @Column(name = "INT_DUE_DATE")
  private String intDueDate;
  @Column(name = "LIQ_DEFER_INTEREST")
  private String liqDeferInterest;
  @Column(name = "BROKER_CODE")
  private String brokerCode;
  @Column(name = "BROKERAGE")
  private String brokerage;
  @Column(name = "BROKER_CCY")
  private String brokerCcy;
  @Column(name = "BROKER_AMOUNT")
  private String brokerAmount;
  @Column(name = "OUR_REMARKS")
  private String ourRemarks;
  @Column(name = "DRAWDOWN_ACCOUNT")
  private String drawdownAccount;
  @Column(name = "PRIN_LIQ_ACCT")
  private String prinLiqAcct;
  @Column(name = "PRIN_BEN_BANK_1")
  private String prinBenBank1;
  @Column(name = "PRIN_BEN_BANK_2")
  private String prinBenBank2;
  @Column(name = "PRIN_ADDRESS")
  private String prinAddress;
  @Column(name = "BENEF_PRIN_ACCT")
  private String benefPrinAcct;
  @Column(name = "INT_LIQ_ACCT")
  private String intLiqAcct;
  @Column(name = "INT_BEN_BANK_1")
  private String intBenBank1;
  @Column(name = "INT_BEN_BANK_2")
  private String intBenBank2;
  @Column(name = "INT_ADDRESS")
  private String intAddress;
  @Column(name = "BEN_INT_ACCT")
  private String benIntAcct;
  @Column(name = "TAX_INTEREST_KEY")
  private String taxInterestKey;
  @Column(name = "LIMIT_REFERENCE")
  private String limitReference;
  @Column(name = "THIRD_PARTY_REF")
  private String thirdPartyRef;
  @Column(name = "CUSTOMER_REF")
  private String customerRef;
  @Column(name = "CUST_REMARKS")
  private String custRemarks;
  @Column(name = "FEDERAL_FUNDS")
  private String federalFunds;
  @Column(name = "DELIVERY_LINK")
  private String deliveryLink;
  @Column(name = "CHRG_LIQ_ACCT")
  private String chrgLiqAcct;
  @Column(name = "CHARGE_CODE")
  private String chargeCode;
  @Column(name = "CHARGE_AMOUNT")
  private String chargeAmount;
  @Column(name = "CURRENCY_MARKET")
  private String currencyMarket;
  @Column(name = "POSITION_TYPE")
  private String positionType;
  @Column(name = "NEG_REF_NUMBER")
  private String negRefNumber;
  @Column(name = "INT_REF_NUMBER")
  private String intRefNumber;
  @Column(name = "MIS_INTEREST_KEY")
  private String misInterestKey;
  @Column(name = "MIS_INTEREST_RATE")
  private String misInterestRate;
  @Column(name = "COUNTRY_RISK")
  private String countryRisk;
  @Column(name = "COUNTRY_EXPOSURE")
  private String countryExposure;
  @Column(name = "MIS_ACCT_OFFICER")
  private String misAcctOfficer;
  @Column(name = "FID_COMM_RATE")
  private String fidCommRate;
  @Column(name = "FID_TOT_COMM_AMNT")
  private String fidTotCommAmnt;
  @Column(name = "FIDUCIARY_BANK")
  private String fiduciaryBank;
  @Column(name = "FID_ASSOC_LD_REF")
  private String fidAssocLdRef;
  @Column(name = "FID_DRAWDOWN_ACCT")
  private String fidDrawdownAcct;
  @Column(name = "FID_PRIN_LIQ_ACCT")
  private String fidPrinLiqAcct;
  @Column(name = "FID_PRIN_BEN_BK_1")
  private String fidPrinBenBk1;
  @Column(name = "FID_PRIN_BEN_BK_2")
  private String fidPrinBenBk2;
  @Column(name = "FID_PRIN_ADD")
  private String fidPrinAdd;
  @Column(name = "FID_BEN_PRIN_AC")
  private String fidBenPrinAc;
  @Column(name = "ACTIVITY_CODE")
  private String activityCode;
  @Column(name = "ADVICE_SENT")
  private String adviceSent;
  @Column(name = "PRIN_INCREASE")
  private String prinIncrease;
  @Column(name = "INCR_EFF_DATE")
  private Date incrEffDate;
  @Column(name = "ROLLOVER_MARKER")
  private String rolloverMarker;
  @Column(name = "ROLLOVER_DATE")
  private Date rolloverDate;
  @Column(name = "NEW_INTEREST_RATE")
  private String newInterestRate;
  @Column(name = "NEW_INTRST_SPREAD")
  private String newIntrstSpread;
  @Column(name = "CAPITALISATION")
  private String capitalisation;
  @Column(name = "CONF_BY_CUST")
  private String confByCust;
  @Column(name = "CONF_BY_BROKER")
  private String confByBroker;
  @Column(name = "SWIFT_COMMON_REF")
  private String swiftCommonRef;
  @Column(name = "STATUS")
  private String status;
  @Column(name = "TOT_INT_TAX")
  private String totIntTax;
  @Column(name = "DEALER_DESK")
  private String dealerDesk;
  @Column(name = "ORIGINAL_FUNCTION")
  private String originalFunction;
  @Column(name = "COMM_RATE_FLAG")
  private String commRateFlag;
  @Column(name = "COMM_AMT_FLAG")
  private String commAmtFlag;
  @Column(name = "PORTFOLIO_NUMBER")
  private String portfolioNumber;
  @Column(name = "BK_TO_BK_INFO")
  private String bkToBkInfo;
  @Column(name = "INT_CCY")
  private String intCcy;
  @Column(name = "INT_CCY_MKT")
  private String intCcyMkt;
  @Column(name = "CHG_TAX_CODE")
  private String chgTaxCode;
  @Column(name = "CHG_TAX_AMT")
  private String chgTaxAmt;
  @Column(name = "CHG_TAX_AMT_LCY")
  private String chgTaxAmtLcy;
  @Column(name = "TOTAL_CHARGE")
  private String totalCharge;
  @Column(name = "TOTAL_TAX_ON_CHG")
  private String totalTaxOnChg;
  @Column(name = "CHG_VALUE_DATE")
  private Date chgValueDate;
  @Column(name = "AUTO_ROLLOVER")
  private String autoRollover;
  @Column(name = "AUTO_CAPITALISE")
  private String autoCapitalise;
  @Column(name = "AUTO_ROLL_TERM")
  private String autoRollTerm;
  @Column(name = "ROLLOVER_INT_RATE")
  private String rolloverIntRate;
  @Column(name = "LINKED_CONTRACT")
  private String linkedContract;
  @Column(name = "LINK_REFERENCE")
  private String linkReference;
  @Column(name = "LIQUIDATION_MODE")
  private String liquidationMode;
  @Column(name = "OVERDUE_STATUS")
  private String overdueStatus;
  @Column(name = "INT_PERIOD_START")
  private Date intPeriodStart;
  @Column(name = "INT_PERIOD_END")
  private Date intPeriodEnd;
  @Column(name = "NEXT_INT_AMOUNT")
  private String nextIntAmount;
  @Column(name = "NEXT_INT_TAX_AMT")
  private String nextIntTaxAmt;
  @Column(name = "NEXT_PRIN_AMOUNT")
  private String nextPrinAmount;
  @Column(name = "ORIG_START_DATE")
  private Date origStartDate;
  @Column(name = "ORIG_MAT_DATE")
  private String origMatDate;
  @Column(name = "PREV_MAT_DATE")
  private Date prevMatDate;
  @Column(name = "MI_FUNDING_DEPT")
  private String miFundingDept;
  @Column(name = "TAX_INTEREST_TYPE")
  private String taxInterestType;
  @Column(name = "CONTRACT_GRP")
  private String contractGrp;
  @Column(name = "PI_INT_KEY")
  private String piIntKey;
  @Column(name = "MERGE_CONTRACT")
  private String mergeContract;
  @Column(name = "MERGE_AMOUNT")
  private String mergeAmount;
  @Column(name = "FINAL_MATURITY")
  private String finalMaturity;
  @Column(name = "FV_RATE_KEY")
  private String fvRateKey;
  @Column(name = "FV_MARGIN_KEY")
  private String fvMarginKey;
  @Column(name = "MATURE_AT_SOD")
  private String matureAtSod;
  @Column(name = "MAX_LEGAL_BAL")
  private String maxLegalBal;
  @Column(name = "GR_INT_TAX_LCY")
  private String grIntTaxLcy;
  @Column(name = "INT_TAX_LCY")
  private String intTaxLcy;
  @Column(name = "GR_INT_TAX_FCY")
  private String grIntTaxFcy;
  @Column(name = "INT_TAX_FCY")
  private String intTaxFcy;
  @Column(name = "EFF_INT_RATE")
  private String effIntRate;
  @Column(name = "MATURED_ONLINE")
  private String maturedOnline;
  @Column(name = "MIS_COF_TYPE")
  private String misCofType;
  @Column(name = "MIS_COF_RATE")
  private String misCofRate;
  @Column(name = "MIS_COF_DEPT")
  private String misCofDept;
  @Column(name = "FUND_ID")
  private String fundId;
  @Column(name = "NEGATIVE_RATE")
  private String negativeRate;
  @Column(name = "SEND_PAYMENT")
  private String sendPayment;
  @Column(name = "INT_SCHEDULE")
  private String intSchedule;
  @Column(name = "NEXT_INT_SCH_AMT")
  private String nextIntSchAmt;
  @Column(name = "ROUNDING_RULE")
  private String roundingRule;
  @Column(name = "SPEC_INT_METHOD")
  private String specIntMethod;
  @Column(name = "IAS_CLASSIFICATION")
  private String iasClassification;
  @Column(name = "SUB_TYPE")
  private String subType;
  @Column(name = "MARKET_RATE")
  private String marketRate;
  @Column(name = "MARKET_MARGIN")
  private String marketMargin;
  @Column(name = "COMPOUND_TYPE")
  private String compoundType;
  @Column(name = "COMPOUND_YLD_MTHD")
  private String compoundYldMthd;
  @Column(name = "RESERVED10")
  private String reserved10;
  @Column(name = "RESERVED9")
  private String reserved9;
  @Column(name = "RESERVED8")
  private String reserved8;
  @Column(name = "RESERVED7")
  private String reserved7;
  @Column(name = "RESERVED6")
  private String reserved6;
  @Column(name = "RESERVED5")
  private String reserved5;
  @Column(name = "RESERVED4")
  private String reserved4;
  @Column(name = "RESERVED3")
  private String reserved3;
  @Column(name = "RESERVED2")
  private String reserved2;
  @Column(name = "RESERVED1")
  private String reserved1;
  @Column(name = "LOCAL_REF")
  private String localRef;
  @Column(name = "STMT_NO")
  private String stmtNo;
  @Column(name = "OVERRIDE")
  private String override;
  @Column(name = "RECORD_STATUS")
  private String recordStatus;
  @Column(name = "CURR_NO")
  private String currNo;
  @Column(name = "INPUTTER")
  private String inputter;
  @Column(name = "DATE_TIME")
  private String dateTime;
  @Column(name = "AUTHORISER")
  private String authoriser;
  @Column(name = "CO_CODE")
  private String coCode;
  @Column(name = "DEPT_CODE")
  private String deptCode;
  @Column(name = "AUDITOR_CODE")
  private String auditorCode;
  @Column(name = "AUDIT_DATE_TIME")
  private String auditDateTime;
  @Column(name = "JRN_FLAG")
  private String jrnFlag;
  @Column(name = "JRN_CREATION_DATE")
  private Date jrnCreationDate;
  @Column(name = "JRN_UPDATING_DATE")
  private Date jrnUpdatingDate;

}
