package com.tcbs.automation.config.poseidon;

public class PoseidonKey {
  public static final String TICKERS_RECENTLY = "TICKERS_RECENTLY";
  public static final String TICKERS_NOTE = "TICKERS_NOTE";

  public static final String CREATED_ID = "CREATED_ID";
  public static final String LOGIN_JWT = "LOGIN_JWT";
  public static final String TCBS_ID = "TCBS_ID";
  public static final String WATCHLISTS = "WATCHLISTS";
  public static final String LIST_CATEGORY_INTERNAL = "LIST_CATEGORY_INTERNAL";
  public static final String WATCHLIST_NAME = "WATCHLIST_NAME";
  public static final String WATCHLIST_TICKERS = "WATCHLIST_TICKERS";

  public static final String POST = "post";
  public static final String PUT = "put";
  public static final String GET = "get";
  public static final String DELETE = "delete";

  public static final String EXPIRED_JWT = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1YXRfYXV0aGVuX3NlcnZpY2UiLCJleHAiOjE2MjM3NDI1NDYsImp0aSI6IiIsImlhdCI6MTYyMzY1NjE0Niwic3ViIjoiMDAwMTMwMDQ4NiIsImN1c3RvZHlJRCI6IjEwNUMzMDA0ODYiLCJlbWFpbCI6Imxpbmh0dHAyQHRlY2hjb21iYW5rLmNvbS52biIsInJvbGVzIjpbImN1c3RvbWVyIiwiQXBwbGljYXRpb24vUk1zIiwiQXBwbGljYXRpb24vd3Nfcm0iLCJBcHBsaWNhdGlvbi9QSS1iZXRhLXVzZXIiLCJybSJdLCJzdGVwdXBfZXhwIjowLCJzb3RwX3NpZ24iOiIiLCJjbGllbnRfa2V5IjoiblR6Sjg4c2RUVlFleWFVdjhHakFRcjFJMDRYTzRRSEUiLCJzZXNzaW9uSUQiOiI4YTQzMjZlZi1kNmEwLTQ1OTQtYWI0ZC01YTMzOTdlM2Q3NjQiLCJhY2NvdW50X3N0YXR1cyI6IjEiLCJvdHAiOiIiLCJvdHBUeXBlIjoiIn0.r4E4Ctdf7DvubKEiN4lyf7ETaFtgoy66wS4PgC8pWDiLMMUXzLE5o9b7Bzni15jFzlkGj2L27ue8Oki8y2K-lXXZfY-CaAazvI6cv1Vh-KhPupdL5tZ0XrJG3NJABI8QSCGmBaZQKsq6EyBI1SOeOtVw_ir4MttcvbKgbh7IABbtSfMkbVH3ymGHk04VKNqQWhZOnvEFZwcsRTv-RZeyh9QFpAA2XCHnqGF8tbCm_0R2g4cR0gWq-A4kDoCBAbeDSdnJP9JeqXGQFnJSYg9_u3Tngvzq144h1clh372n8HJjW6O866aLH5B8D1THS1J3v-VKWttstAcErsdyQoovMA";
  public static final String INVALID_XAPIKEY = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1YXRfYXV0aGVuX3NlcnZpY2UiLCJleHAiOjE2MjM3NDI1NDYsImp0aSI6IiIsImlhdCI6MTYyMzY1NjE0Niwic3ViIjoiMDAwMTMwMDQ4NiIsImN1c3RvZHlJRCI6IjEwNUMzMDA0ODYiLCJlbWFpbCI6Imxpbmh0dHAyQHRlY2hjb21iYW5rLmNvbS52biIsInJvbGVzIjpbImN1c3RvbWVyIiwiQXBwbGljYXRpb24vUk1zIiwiQXBwbGljYXRpb24vd3Nfcm0iLCJBcHBsaWNhdGlvbi9QSS1iZXRhLXVzZXIiLCJybSJdLCJzdGVwdXBfZXhwIjowLCJzb3RwX3NpZ24iOiIiLCJjbGllbnRfa2V5IjoiblR6Sjg4c2RUVlFleWFVdjhHakFRcjFJMDRYTzRRSEUiLCJzZXNzaW9uSUQiOiI4YTQzMjZlZi1kNmEwLTQ1OTQtYWI0ZC01YTMzOTdlM2Q3NjQiLCJhY2NvdW50X3N0YXR1cyI6IjEiLCJvdHAiOiIiLCJvdHBUeXBlIjoiIn0.r4E4Ctdf7DvubKEiN4lyf7ETaFtgoy66wS4PgC8pWDiLMMUXzLE5o9b7Bzni15jFzlkGj2L27ue8Oki8y2K-lXXZfY-CaAazvI6cv1Vh-KhPupdL5tZ0XrJG3NJABI8QSCGmBaZQKsq6EyBI1SOeOtVw_ir4MttcvbKgbh7IABbtSfMkbVH3ymGHk04VKNqQWhZOnvEFZwcsRTv-RZeyh9QFpAA2XCHnqGF8tbCm_0R2g4cR0gWq-A4kDoCBAbeDSdnJP9JeqXGQFnJSYg9_u3Tngvzq144h1clh372n8HJjW6O866aLH5B8D1THS1J3v-VKWttstAcErsdyQoovMA";
}
