package com.tcbs.automation.config.ixu;

public class IxuKey {
  /*====================iXu===============================*/
  public static final String IXU_LP_API = "loyalPointFromApi";
  public static final String IXU_LP_DB = "loyalPointFromDB";
  public static final String IXU_GL = "updateGL";
  public static final String IXU_HISTORY_POINT = "history point";

  public static final String ODIN_RATE_HOLDING_FUND = "rateHoldingFundFromApi";
  public static final String ODM_RATE_HOLDING_FUND = "rateHoldingFundFromOdm";
  public static final String CALCULATE_PRICING = "calculatePricing";
  public static final String ODIN_RANKING_POINT = "ODIN_RANKING_POINT";
  public static final String ODIN_POINT_IN_CURRENT_MEMBERSHIP = "ODIN_POINT_IN_CURRENT_MEMBERSHIP";
  public static final String ODIN_LIST_TRANSACTION_REWARD_IXU = "ODIN_LIST_TRANSACTION_REWARD_IXU";
  public static final String ODIN_GET_CUSTOMER_BIRTHDAY = "ODIN_GET_CUSTOMER_BIRTHDAY";
  public static final String ODIN_NUMBER_NOTIFY_MESSAGE = "ODIN_NUMBER_NOTIFY_MESSAGE";
  public static final String ODIN_CALCULATOR_LIMIT_JOB_KEY = "ODIN_CALCULATOR_LIMIT_JOB_KEY";
  public static final String ODIN_CALCULATOR_LIMIT_JOB_KEY_WITH_METHOD = "ODIN_CALCULATOR_LIMIT_JOB_KEY_WITH_METHOD";


  public static final String ORDER_SERVICE_CREATE = "ORDER_SERVICE_CREATE";
  public static final String QUERY_LIST_ORDER = "QUERY_LIST_ORDER";
  public static final String ORDER_ID = "ORDER_ID";
  public static final String UPDATE_ORDER_BY_ID = "UPDATE_ORDER_BY_ID";

  public static final String IPARTNER_CREATE_SURVEY = "IPARTNER_CREATE_SURVEY";

  public static final String JARVIS_RESP = "JARVIS_RESP";
  public static final String FILE_NAME_FORMAT = "OLSTXNRF_tcbs_yyyymmdd_01_RETURN.TXT";
  public static final String FILE_TEST_SOURCE = "src/test/resources/jarvis/getReturnVinID.txt";

  public static final String HULK_DELETE_FILE = "HULK_DELETE_FILE";
  public static final String HULK_POST_FILE = "HULK_POST_FILE";
  public static final String HULK_GET_FILE = "HULK_GET_FILE";
  public static final String HULK_GET_FOLDER = "HULK_GET_FOLDER";

  public static final String LATEST_ORDER = "LATEST_ORDER";
  public static final String CANCEL_STATUS = "CANCEL_STATUS";

  public static final String ACTIVATE_INVALID_TOKEN = "ACTIVATE_INVALID_TOKEN";
  public static final String RETRIEVE_EMAIL_USING_FORGOT_PWD = "RETRIEVE_EMAIL_USING_FORGOT_PWD";
  public static final String PORTFOLIO_AFC = "PORTFOLIO_AFC";
  public static final String PORTFOLIO_AFM = "PORTFOLIO_AFM";
  public static final String PORTFOLIO_REPLY_ORDER_MESSAGES = "PORTFOLIO_AFM";

  public static final String RESULT_TRADING_BY_SOURCE_INFORMATION = "RESULT_TRADING_BY_SOURCE_INFORMATION";

  public static final String MANUAL_TRANSACTION_RECORD = "MANUAL_TRANSACTION_RECORD";
  public static final String MANUAL_TRANSACTION_HISTORY_RECORD = "MANUAL_TRANSACTION_HISTORY_RECORD";
  public static final String SEARCH_MANUAL_TRANSACTION_RESPONSE = "SEARCH_MANUAL_TRANSACTION_RESPONSE";
  public static final String GET_TOP_REFERAL_RESPONSE = "GET_TOP_REFERAL_RESPONSE";
  public static final String UPDATE_MANUAL_TRANSACTION_STATUS_RESPONSE = "UPDATE_MANUAL_TRANSACTION_STATUS_RESPONSE";
  public static final String GET_MEMBERSHIP_BY_105C_RESPONSE = "GET_MEMBERSHIP_BY_105C_RESPONSE";
  public static final String GET_MANUAL_TRANSACTION_DETAIL_RESPONSE = "GET_MANUAL_TRANSACTION_DETAIL_RESPONSE";
  public static final String GET_ALL_CAMPAIGNS_RESPONSE = "GET_ALL_CAMPAIGN_RESPONSE";
  public static final String FORBIDDEN_RESPONSE = "FORBIDDEN_RESPONSE";
  public static final String GET_ALL_CAMPAIGNS_DB = "GET_ALL_CAMPAIGN_DB";
  public static final String CODE_STATUS_CREATE_MANUAL_WITH_FILE = "CODE_STATUS_CREATE_MANUAL_WITH_FILE";
  public static final String RESPONE_CREATE_MANUAL_WITH_FILE = "RESPONE_CREATE_MANUAL_WITH_FILE";
  public static final String DB_FILE_STATUS = "DB_FILE_STATUS";
  public static final String ODIN_RB_CAMPAIGN_RECORD = "ODIN_RB_CAMPAIGN_RECORD";
  public static final String ODIN_FILE_STATUS_RESPONSE = "ODIN_FILE_STATUAS";
  public static final String ODIN_UPDATE_MANUAL_REQUEST = "ODIN_UPDATE_MANUAL_REQUEST";
  public static final String ODIN_MARGIN_ACCUMULATION_JOB_KEY = "ODIN_MARGIN_ACCUMULATION_JOB_KEY";
  public static final String ODIN_MARGIN_CONSUME_JOB_KEY = "ODIN_MARGIN_CONSUME_JOB_KEY";
  public static final String ODIN_PRO_INVESTMENT_JOB_KEY = "ODIN_PRO_INVESTMENT_JOB_KEY";
  public static final String ODIN_DOCUMENT_KEY = "ODIN_DOCUMENT_KEY";
  public static final String ODIN_DOCUMENT_BASE64_KEY = "ODIN_DOCUMENT_BASE64_KEY";
  public static final String ODIN_REFUND_ICONNECT_CALC = "ODIN_REFUND_ICONNECT_CALC";
  public static final String GET_CATEGORY_POINT_LIMIT = "ODIN_GET_CATEGORY_POINT_LIMIT";
  public static final String ODIN_CLOSE_ACCOUNT = "ODIN_CLOSE_ACCOUNT";
  public static final String ODIN_RECALL_IFUND_ORDERS_KEY = "ODIN_RECALL_IFUND_ORDERS_KEY";
  public static final String ODIN_GET_PAYMENT_PERIOD = "ODIN_GET_PAYMENT_PERIOD";

  // wanda key
  public static final String WANDA_GET_GENERAL_TRANSACTION = "WANDA_GET_GENERAL_TRANSACTION";
  public static final String WANDA_GET_TRANSACTION_CANCEL = "WANDA_GET_TRANSACTION_CANCEL";
  public static final String WANDA_GET_TRANSACTION_CHANGE_STATUS = "WANDA_GET_TRANSACTION_CHANGE_STATUS";
  public static final String WANDA_OVER_LIMIT_ACTION = "WANDA_OVER_LIMIT_ACTION";
  public static final String WANDA_LIMIT_HISTORY = "WANDA_LIMIT_HISTORY";
  public static final String WANDA_GET_TRANSACTION_RETRY = "WANDA_GET_TRANSACTION_RETRY";
  public static final String WANDA_GET_DETAIL_IXU_BY_TCBSID_RESP = "WANDA_GET_DETAIL_IXU_BY_TCBSID_RESP";
  public static final String WANDA_GET_DETAIL_GENERAL_TX_BY_ID_RESP = "WANDA_GET_DETAIL_GENERAL_TX_BY_ID_RESP";
  public static final String WANDA_GET_IXU_TX_HISTORY_BY_REFID_RESP = "WANDA_GET_IXU_TX_HISTORY_BY_REFID_RESP";
  public static final String WANDA_ADD_BLACKLIST_RES = "WANDA_ADD_BLACKLIST_RES";
  public static final String WANDA_DELETE_BLACKLIST_RES = "WANDA_ADD_BLACKLIST_RES";
  public static final String WANDA_CHECK_IBER_API = "WANDA_CHECK_IBER_API";
  public static final String WANDA_NOTIFY_NEW_DEPLOYMENT_KEY = "WANDA_NOTIFY_NEW_DEPLOYMENT_KEY";
  public static final String WANDA_CHANGE_LIMITED_DAILY_POINT_KEY = "WANDA_CHANGE_LIMITED_DAILY_POINT_KEY";
  public static final String WANDA_RESET_LIMITED_DAILY_KEY = "WANDA_RESET_LIMITED_DAILY_KEY";

  public static final String HEIMDALL_IXU_GENERAL_LEDGER_RECORD = "HEIMDALL_IXU_GENERAL_LEDGER_RECORD";
  public static final String HEIMDALL_IXU_MEMBERSHIP_TYPE_RECORD = "HEIMDALL_IXU_MEMBERSHIP_TYPE_RECORD";
  public static final String HEIMDALL_GET_SALE_TRANSACTION = "HEIMDALL_GET_SALE_TRANSACTION";
  public static final String HEIMDALL_GET_BATCH_SALE_TRANSACTION = "HEIMDALL_GET_BATCH_SALE_TRANSACTION";
  public static final String HEIMDALL_GET_SALE_TRANSACTION_BLOCK_AND_UNBLOCK = "HEIMDALL_GET_SALE_TRANSACTION_BLOCK_AND_UNBLOCK";
  public static final String HEIMDALL_GET_CURRENT_BALACE = "HEIMDALL_GET_CURRENT_BALACE";
  public static final String HEIMDALL_GET_TXHISTOTY_LIST = "HEIMDALL_GET_TXHISTOTY_LIST";
  public static final String HEIMDALL_GET_BALANCES = "GET_BALANCE";
  public static final String HEIMDALL_UPDATE_MEMBERSHIP = "HEIMDALL_UPDATE_MEMBERSHIP";
  public static final String HEIMDALL_GET_MEMBERSHIP = "HEIMDALL_GET_MEMBERSHIP";
  public static final String HEIMDALL_GET_10000_MEMBERSHIP = "HEIMDALL_GET_10000_MEMBERSHIP";
  public static final String HEIMDALL_GET_MEMBERSHIP_LIST = "HEIMDALL_GET_MEMBERSHIP_LIST";
  public static final String HEIMDALL_GET_HISTORIES = "HEIMDALL_GET_HISTORIES";
  public static final String HEIMDALL_GET_TXHISTOTY_LIST_PAGING = "HEIMDALL_GET_TXHISTOTY_LIST_PAGING";
  public static final String HEIMDALL_UPDATE_CODE105C_IGL_JOB_KEY = "HEIMDALL_UPDATE_CODE105C_IGL_JOB_KEY";
  public static final String HEIMDALL_CHECK_ASSETS = "HEIMDALL_CHECK_ASSETS";
  public static final String HEIMDALL_CHECK_ASS3TS = "HEIMDALL_CHECK_ASS3TS";
  public static final String HEIMDALL_GET_BLOCK_TRANSACTIONS = "HEIMDALL_GET_BLOCK_TRANSACTIONS";
  public static final String HEIMDALL_CLEAR_RANKING = "HEIMDALL_CLEAR_RANKING";

  public static final String HAWKEYE_GET_BALACE = "HAWKEYE_GET_BALACE";

  public static final String IRONMAN_VINID_SALE_TRANSACTION = "IRONMAN_VINID_SALE_TRANSACTION";
  public static final String IRONMAN_VINID_SALE_TRANSACTION_V2 = "IRONMAN_VINID_SALE_TRANSACTION_V2";
  public static final String IRONMAN_CURRENT_POINT = "IRONMAN_CURRENT_POINT";
  public static final String IRONMAN_POINTS = "IRONMAN_POINTS";
  public static final String IRONMAN_VINID_MEMBER_PROFILE = "IRONMAN_VINID_MEMBER_PROFILE";
  public static final String IRONMAN_EXCHANGE_IXU_TO_CASH_RESPONSE = "IRONMAN_EXCHANGE_IXU_TO_CASH_RESPONSE";
  public static final String IRONMAN_CREATE_PLAN_RESPONSE = "IRONMAN_EXCHANGE_IXU_TO_CASH_RESPONSE";
  public static final String IRONMAN_CHANGE_STATUS_RESPONSE = "IRONMAN_EXCHANGE_IXU_TO_CASH_RESPONSE";
  public static final String IRONMAN_GET_INFO_PLAN_RESPONSE = "IRONMAN_GET_INFO_PLAN_RESPONSE";
  public static final String IRONMAN_RETRY_IXU_TO_CASH_RESPONSE = "IRONMAN_RETRY_IXU_TO_CASH_RESPONSE";
  public static final String IRONMAN_CANCEL_IXU_TO_CASH_RESPONSE = "IRONMAN_CANCEL_IXU_TO_CASH_RESPONSE";
  public static final String IRONMAN_TRANSFER_IXU = "IRONMAN_TRANSFER_IXU";
  public static final String IRONMAN_TRANSFER_XU = "IRONMAN_TRANSFER_XU";
  public static final String IRONMAN_TRANSFER_IXU_VERIFY = "IRONMAN_TRANSFER_IXU_VERIFY";
  public static final String IRONMAN_TRANSFER_IXU_TEMPLATE_NOTIFY = "IRONMAN_TRANSFER_IXU_TEMPLATE_NOTIFY";
  public static final String IRONMAN_TRANSFER_IXU_SCANNING_NOTIFICATION = "IRONMAN_TRANSFER_IXU_SCANNING_NOTIFICATION";
  public static final String IRONMAN_TRANSFER_IXU_CUSTOMER_VERIFICATION = "IRONMAN_TRANSFER_IXU_CUSTOMER_VERIFICATION";
  public static final String IRONMAN_GENERAL_TRANSACTION = "IRONMAN_GENERAL_TRANSACTION";
  public static final String IRONMAN_GENERAL_TRANSACTION_HISTORY = "IRONMAN_GENERAL_TRANSACTION_HISTORY";
  public static final String IRONMAN_TRASACTION_CASH = "IRONMAN_TRASACTION_CASH";
  public static final String IRONMAN_TRASACTION_RETTRY_VINID_RESP = "IRONMAN_TRASACTION_RETTRY_VINID_RESP";
  public static final String IRONMAN_ORDER_FUND_RESPONSE = "IRONMAN_ORDER_FUND_RESPONSE";
  public static final String IRONMAN_ORDER_FUND_GET_CUSTOMERS_RESPONSE = "IRONMAN_ORDER_FUND_GET_CUSTOMERS_RESPONSE";


  // JARIVS
  public static final String JARVIS_TRANSACTION_REFUND = "JARVIS_TRANSACTION_REFUND";
  public static final String JARVIS_TRANSACTION_TAX = "JARVIS_TRANSACTION_TAX";
  //WSO2IS
  public static final String WSO2IS_LOGIN_API_REPONSE = "WSO2IS_LOGIN_API_REPONSE";
}
