package com.tcbs.automation.config.coco;

public class CocoServiceKey {
  private CocoServiceKey() {}
  public static final String COCO_ACCOUNT_PUBLIC_STATUS_DATA = "COCO_ACCOUNT_PUBLIC_STATUS_DATA";

  public static final String COCO_ACCOUNT_PUBLIC_INTERACT_DATA = "COCO_ACCOUNT_PUBLIC_INTERACT_DATA";

  public static final String COCO_ORDERS_HISTORY_DATA = "COCO_ORDERS_HISTORY_DATA";
  public static final String COCO_ORDERS_SUMMARY_DATA = "COCO_ORDERS_SUMMARY_DATA";
  public static final String COCO_ACCOUNT_ORDERS_STATS_DATA = "COCO_ACCOUNT_ORDERS_STATS_DATA";

  public static final String COCO_PERFORMANCE_HISTORY_DATA = "COCO_PERFORMANCE_HISTORY_DATA";
  public static final String COCO_PERFORMANCE_INDICATORS_DATA = "COCO_PERFORMANCE_INDICATORS_DATA";
  public static final String COCO_PERFORMANCE_PNL_DATA = "COCO_PERFORMANCE_PNL_DATA";
  public static final String COCO_PERFORMANCE_SUMMARY_METRICS_DATA = "COCO_PERFORMANCE_SUMMARY_METRICS_DATA";

  public static final String COCO_CUSTOMERS_PORTFOLIO_DATA = "COCO_CUSTOMERS_PORTFOLIO";

  public static final String COCO_ACCOUNT_ORDERS_HISTORY_DATA = "COCO_ACCOUNT_ORDERS_HISTORY_DATA";
  public static final String COCO_ACCOUNT_ORDERS_SUMMARY_DATA = "COCO_ACCOUNT_ORDERS_SUMMARY_DATA";

  public static final String COCO_ACCOUNT_PERFORMANCE_HISTORY_DATA = "COCO_ACCOUNT_PERFORMANCE_HISTORY_DATA";
  public static final String COCO_ACCOUNT_PERFORMANCE_INDICATORS_DATA = "COCO_ACCOUNT_PERFORMANCE_INDICATORS_DATA";
  public static final String COCO_ACCOUNT_PERFORMANCE_PNL_DATA = "COCO_ACCOUNT_PERFORMANCE_PNL_DATA";
  public static final String COCO_ACCOUNT_PERFORMANCE_SUMMARY_METRICS_DATA = "COCO_ACCOUNT_PERFORMANCE_SUMMARY_METRICS_DATA";
  public static final String COCO_ACCOUNT_PORTFOLIO_DATA = "COCO_ACCOUNT_PORTFOLIO_DATA";

  public static final String COCO_INTERNAL_ACCOUNT_PERFORMANCE_DATA = "COCO_INTERNAL_ACCOUNT_PERFORMANCE_DATA";
  public static final String COCO_INTERNAL_ACCOUNT_INDICES_DATA = "COCO_INTERNAL_ACCOUNT_INDICES_DATA";

  public static final String COCO_COPYING_ASSET_DATA = "COCO_COPYING_ASSET_DATA";
  public static final String COCO_COPYING_ASSET_OF_A_COPY_DATA = "COCO_COPYING_ASSET_OF_A_COPY_DATA";

  public static final String COCO_SHARE_TRADER_BASIC_INFO_DATA = "COCO_SHARE_TRADER_BASIC_INFO_DATA";
  public static final String COCO_SHARE_TRADER_PROFILE_INDEX_DATA = "COCO_SHARE_TRADER_PROFILE_INDEX_DATA";

  public static final String COCO_COPYING_HISTORY_DATA = "COCO_COPYING_HISTORY_DATA";
  public static final String COCO_FOLLOWING_TRADERS_DATA = "COCO_FOLLOWING_TRADERS_DATA";

  public static final String COCO_TRADERS_CHART_DATA = "COCO_TRADERS_CHART_DATA";
  public static final String COCO_TRADERS_TOPS_DATA = "COCO_TRADERS_TOPS_DATA";

  public static final String COCO_TRADERS_BASIC_INFO_DATA = "COCO_TRADERS_BASIC_INFO_DATA";
  public static final String COCO_TRADERS_PROFILE_INDEX_DATA = "COCO_TRADERS_PROFILE_INDEX_DATA";
  public static final String COCO_TRADERS_PROFILE_SUMMARY_DATA = "COCO_TRADERS_PROFILE_SUMMARY_DATA";
  public static final String COCO_TRADERS_VIEW_INDEX_DATA = "COCO_TRADERS_VIEW_INDEX_DATA";
  public static final String COCO_TRADERS_FILTER_DATA = "COCO_TRADERS_FILTER_DATA";
  public static final String COCO_TRADERS_STRATEGY_DATA = "COCO_TRADERS_STRATEGY_DATA";
  public static final String COCO_TRADERS_STRATEGY_DATA1 = "COCO_TRADERS_STRATEGY_DATA1";
  public static final String COCO_TRADERS_RATING_DATA = "COCO_TRADERS_RATING_DATA";
  public static final String COCO_TRADERS_RATING_DATA1 = "COCO_TRADERS_RATING_DATA1";
  public static final String COCO_VERIFY_COPY_DATA = "COCO_VERIFY_COPY_DATA";
  public static final String COCO_VERIFY_STOP_TRADER_DATA = "COCO_VERIFY_STOP_TRADER_DATA";
  public static final String COCO_GET_TRADERS_FEE_CONFIG_DATA = "COCO_GET_TRADERS_FEE_CONFIG_DATA";
  public static final String COCO_POST_TRADERS_FEE_CONFIG_DATA = "COCO_POST_TRADERS_FEE_CONFIG_DATA";
  public static final String COCO_DEL_TRADERS_FEE_CONFIG_DATA = "COCO_DEL_TRADERS_FEE_CONFIG_DATA";
  public static final String COCO_GET_TRADERS_CONFIG_DATA = "COCO_GET_TRADERS_CONFIG_DATA";
  public static final String COCO_POST_TRADERS_CONFIG_DATA = "COCO_POST_TRADERS_CONFIG_DATA";
  public static final String COCO_RENEW_TRADER_DATA = "COCO_RENEW_TRADER_DATA";

  public static final String COCO_TRADER_ORDER_DATA = "COCO_TRADER_ORDER_DATA";
  public static final String COCO_CASH_STATEMENT_DATA = "COCO_CASH_STATEMENT_DATA";
  public static final String COCO_STOCK_STATEMENT_DATA = "COCO_STOCK_STATEMENT_DATA";
  public static final String COCO_CASH_BOD_BALANCE_DATA = "COCO_CASH_BOD_BALANCE_DATA";
  public static final String COCO_GET_CRITERIA_GROUP_DATA = "COCO_GET_CRITERIA_GROUP_DATA";
  public static final String COCO_UPDATE_CRITERIA_GROUP_DATA = "COCO_UPDATE_CRITERIA_GROUP_DATA";
  public static final String COCO_GET_CRITERIA_GROUPS_DATA = "COCO_GET_CRITERIA_GROUPS_DATA";
  public static final String COCO_SE_DATA = "COCO_SE_DATA";
  public static final String COCO_CASH_INVESTMENT_DATA = "COCO_CASH_INVESTMENT_DATA";
  public static final String COCO_ACCOUNTS_DATA = "COCO_ACCOUNTS_DATA";
  public static final String COCO_RANKS_DATA = "COCO_RANKS_DATA";
  public static final String COCO_RANK_DATA = "COCO_RANK_DATA";
  public static final String COCO_UPDATE_RANK_DATA = "COCO_UPDATE_RANK_DATA";
  public static final String COCO_FILTER_WHITELIST_DATA = "COCO_FILTER_WHITELIST_DATA";
  public static final String COCO_FILTER_WHITELIST_HISTORY_DATA = "COCO_FILTER_WHITELIST_HISTORY_DATA";
  public static final String COCO_FILTER_COPIERS_DATA = "COCO_FILTER_COPIERS_DATA";
  public static final String COCO_FILTER_TRADERS_DATA = "COCO_FILTER_TRADERS_DATA";
  public static final String COCO_COPIER_ORDER_DATA = "COCO_COPIER_ORDER_DATA";

  public static final String COCO_WHITELIST_ARR = "COCO_WHITELIST_ARR";
  public static final String COCO_TRADER_UTILS_JOIN_TIME_DATA = "COCO_TRADER_UTILS_JOIN_TIME_DATA";
}
