package com.tcbs.automation.config.devmana;

public class DevmanaKey {
  public static final String DEVMANA_REGISTER_RESPONSE = "DEVMANA_REGISTER_RESPONSE";
  public static final String DEVMANA_FIREBASE_GROUP_RESPONSE = "DEVMANA_FIREBASE_GROUP_RESPONSE";
  public static final String DEVMANA_FIREBASE_TOKEN_RESPONSE = "DEVMANA_FIREBASE_TOKEN_RESPONSE";
  public static final String DEVMANA_UNREGISTER_RESPONSE = "DEVMANA_UNREGISTER_RESPONSE";
  public static final String DEVMANA_GROUP_INFO = "DEVMANA_GROUP_INFO";
  public static final String DEVMANA_UNICAST_RESPONSE = "DEVMANA_UNICAST_RESPONSE";
  public static final String DEVMANA_MULTICAST_RESPONSE = "DEVMANA_MULTICAST_RESPONSE";
  public static final String DEVMANA_BROADCAST_RESPONSE = "DEVMANA_BROADCAST_RESPONSE";
  public static final String DEVMANA_CHECK_RESPONSE = "DEVMANA_CHECK_RESPONSE";
  public static final String DEVMANA_MESSAGE_HISTORY_RESPONSE = "DEVMANA_MESSAGE_HISTORY_RESPONSE";
  public static final String DEVMANA_REGISTER_INFO_RESPONSE = "DEVMANA_REGISTER_INFO_RESPONSE";
  public static final String DEVMANA_RETRY_REGISTER_RESPONSE = "DEVMANA_RETRY_REGISTER_RESPONSE";
  public static final String DEVMANA_SUBSCRIBE_RESPONSE = "DEVMANA_SUBSCRIBE_RESPONSE";
  public static final String DEVMANA_UNSUBSCRIBE_RESPONSE = "DEVMANA_UNSUBSCRIBE_RESPONSE";
  public static final String DEVMANA_RESEND_RESPONSE = "DEVMANA_RESEND_RESPONSE";
}
